const youtubeExample1Data = {
    videoId: "3sXrWz763J8",
    videoUrl: "https://www.youtube.com/watch?v=3sXrWz763J8",
    embedcode: "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/3sXrWz763J8?si=05u6B9OqkUQJACYs\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>",
    title: "Full Tutorial: Play Piano by Ear",
    cantoneseTitle: "全面靠聽力彈琴教程",
    transcript: [
        { time: "0:00", text: "[Music]", translation: "[音樂]" },
        { time: "0:05", text: "Welcome to this comprehensive guide on learning to play piano by ear.", translation: "歡迎來到呢個全面指南，學靠聽力彈琴" },
        { time: "0:10", text: "If you've ever wondered how musicians can just hear a song and play it,", translation: "如果你曾經好奇音樂人點樣可以只係聽首歌就彈到" },
        { time: "0:15", text: "this video will break down exactly how that works.", translation: "呢條片會詳細解釋點樣做到" },
        { time: "0:20", text: "The good news is that music is actually much simpler than you think.", translation: "好消息係音樂其實比你以為嘅簡單好多" },
        { time: "0:25", text: "Think of music as a language, but unlike English which has 170,000 words,", translation: "當音樂係一種語言，但同英文有17萬個字唔同" },
        { time: "0:30", text: "music only has about 14 sounds you need to learn.", translation: "音樂只需要學大約14個聲音" },
        { time: "0:35", text: "That's it. Just 14 sounds.", translation: "就係咁。只係14個聲音" },
        { time: "0:40", text: "Those 14 sounds are: 7 melody notes and 7 chords.", translation: "呢14個聲音係：7個旋律音同7個和弦" },
        { time: "0:45", text: "The 7 melody notes are Do, Re, Mi, Fa, So, La, Ti.", translation: "7個旋律音係Do、Re、Mi、Fa、So、La、Ti" },
        { time: "0:50", text: "And the 7 chords are numbered 1 through 7: I, ii, iii, IV, V, vi, vii.", translation: "7個和弦係1到7：I、ii、iii、IV、V、vi、vii" },
        { time: "0:55", text: "That's the entire language of music right there.", translation: "就係音樂語言全部" },
        { time: "1:00", text: "Now, any song you want to play is made up of two things:", translation: "而家，任何你想彈嘅歌都係由兩樣嘢組成：" },
        { time: "1:05", text: "melody and chords. That's it.", translation: "旋律同和弦。就係咁" },
        { time: "1:10", text: "So to train your ear, you need to train these two areas separately.", translation: "所以要訓練你隻耳，你需要分開訓練呢兩個範疇" },
        { time: "1:15", text: "Let's start with Phase I: Understanding the Language of Music.", translation: "我哋由第一階段開始：理解音樂語言" },
        { time: "1:20", text: "As I mentioned, you only need to learn 14 sounds total.", translation: "正如我提到，你只需要學總共14個聲音" },
        { time: "1:25", text: "Seven melody notes and seven chords.", translation: "七個旋律音同七個和弦" },
        { time: "1:30", text: "This is much simpler than learning a spoken language.", translation: "比學口語簡單好多" },
        { time: "1:35", text: "Let me show you what I mean.", translation: "等我示範俾你睇" },
        { time: "1:40", text: "[Plays Do-Re-Mi-Fa-So-La-Ti-Do]", translation: "[彈Do-Re-Mi-Fa-So-La-Ti-Do]" },
        { time: "1:50", text: "That's your seven melody notes right there.", translation: "就係你嘅七個旋律音" },
        { time: "1:55", text: "And now let me show you the seven chords.", translation: "而家等我示範七個和弦" },
        { time: "2:00", text: "[Plays I, ii, iii, IV, V, vi, vii chords]", translation: "[彈I、ii、iii、IV、V、vi、vii和弦]" },
        { time: "2:15", text: "That's it. That's the entire language.", translation: "就係咁。就係全部語言" },
        { time: "2:20", text: "Now let's move to Phase II: Music Theory Basics.", translation: "而家我哋去第二階段：音樂理論基礎" },
        { time: "2:25", text: "First, let's talk about melodies.", translation: "首先，我哋講下旋律" },
        { time: "2:30", text: "Melodies come from scales.", translation: "旋律來自音階" },
        { time: "2:35", text: "A scale is just those seven notes: Do-Re-Mi-Fa-So-La-Ti.", translation: "音階就係呢七個音：Do-Re-Mi-Fa-So-La-Ti" },
        { time: "2:40", text: "Melodies are just different patterns of these scale notes.", translation: "旋律就係呢啲音階音嘅唔同組合" },
        { time: "2:45", text: "Many songs use just three notes: Do, Re, and Mi.", translation: "好多歌只係用三個音：Do、Re、Mi" },
        { time: "2:50", text: "Think about Journey's 'Don't Stop Believin'',", translation: "諗下Journey嘅'Don't Stop Believin''" },
        { time: "2:55", text: "or songs by The Chainsmokers, or even 'How Far I'll Go' from Moana.", translation: "或者The Chainsmokers嘅歌，甚至Moana嘅'How Far I'll Go'" },
        { time: "3:00", text: "They all use just Do-Re-Mi in different patterns.", translation: "佢哋都只係用Do-Re-Mi，唔同組合" },
        { time: "3:05", text: "Now, what about chords?", translation: "而家，和弦呢？" },
        { time: "3:10", text: "Chords are also built from the scale.", translation: "和弦都係由音階建立" },
        { time: "3:15", text: "We build chords using an 'every other note' pattern.", translation: "我哋用'隔一個音'模式建立和弦" },
        { time: "3:20", text: "Let me show you.", translation: "等我示範" },
        { time: "3:25", text: "If we start on Do and take every other note:", translation: "如果我哋由Do開始，隔一個音：" },
        { time: "3:30", text: "[Plays Do-Mi-So]", translation: "[彈Do-Mi-So]" },
        { time: "3:35", text: "That's the I chord, or the one chord.", translation: "就係I和弦，或者一級和弦" },
        { time: "3:40", text: "If we start on Re:", translation: "如果我哋由Re開始：" },
        { time: "3:45", text: "[Plays Re-Fa-La]", translation: "[彈Re-Fa-La]" },
        { time: "3:50", text: "That's the ii chord, or the two chord.", translation: "就係ii和弦，或者二級和弦" },
        { time: "3:55", text: "And so on for each note in the scale.", translation: "音階每個音都係咁" },
        { time: "4:00", text: "Each scale note can become a chord.", translation: "每個音階音都可以變成和弦" },
        { time: "4:05", text: "Do becomes the I chord, Re becomes the ii chord,", translation: "Do變成I和弦，Re變成ii和弦" },
        { time: "4:10", text: "Mi becomes the iii chord, and so on.", translation: "Mi變成iii和弦，如此類推" },
        { time: "4:15", text: "Now let's get into Phase III: Training Melodies.", translation: "而家我哋進入第三階段：訓練旋律" },
        { time: "4:20", text: "There are three main approaches to training your ear for melodies.", translation: "訓練旋律聽力有三個主要方法" },
        { time: "4:25", text: "The first is interval training.", translation: "第一個係音程訓練" },
        { time: "4:30", text: "Intervals are the spacing between notes.", translation: "音程係音之間嘅距離" },
        { time: "4:35", text: "A second is two notes apart, a third is three notes apart,", translation: "二度係兩個音距離，三度係三個音距離" },
        { time: "4:40", text: "and so on.", translation: "如此類推" },
        { time: "4:45", text: "The method is simple: sing Do, then sing the interval, then back to Do.", translation: "方法好簡單：唱Do，然後唱音程，然後返去Do" },
        { time: "4:50", text: "Let me demonstrate.", translation: "等我示範" },
        { time: "4:55", text: "[Sings Do-Re-Do]", translation: "[唱Do-Re-Do]" },
        { time: "5:00", text: "That's a second interval.", translation: "就係二度音程" },
        { time: "5:05", text: "[Sings Do-Mi-Do]", translation: "[唱Do-Mi-Do]" },
        { time: "5:10", text: "That's a third interval.", translation: "就係三度音程" },
        { time: "5:15", text: "Practice each interval twice: first listen, then sing along.", translation: "每個音程練習兩次：首先聽，然後一齊唱" },
        { time: "5:20", text: "But here's the critical part:", translation: "但係關鍵係：" },
        { time: "5:25", text: "You must sing without the piano first, then check yourself.", translation: "你一定要先冇鋼琴唱，然後檢查自己" },
        { time: "5:30", text: "The goal is to sing each interval acapella accurately.", translation: "目標係無伴奏準確唱每個音程" },
        { time: "5:35", text: "Now, the second approach is melody chunks.", translation: "而家，第二個方法係旋律片段" },
        { time: "5:40", text: "This is the MOST IMPORTANT part, so spend the majority of your time here.", translation: "呢個係最重要部分，所以用大部分時間喺度" },
        { time: "5:45", text: "Real songs don't just use single intervals.", translation: "真實歌曲唔只係用單一音程" },
        { time: "5:50", text: "They use note sequences or chunks.", translation: "佢哋用音序列或片段" },
        { time: "5:55", text: "The method is: pick random note combinations,", translation: "方法係：揀隨機音組合" },
        { time: "6:00", text: "try to sing them, then check with the piano.", translation: "試唱佢哋，然後用鋼琴檢查" },
        { time: "6:05", text: "For example: Do-Re-Mi.", translation: "例如：Do-Re-Mi" },
        { time: "6:10", text: "[Sings Do-Re-Mi]", translation: "[唱Do-Re-Mi]" },
        { time: "6:15", text: "Or Do-Mi-So.", translation: "或者Do-Mi-So" },
        { time: "6:20", text: "[Sings Do-Mi-So]", translation: "[唱Do-Mi-So]" },
        { time: "6:25", text: "Or So-La-So-Fa-Mi-Fa-Mi-Re-Do.", translation: "或者So-La-So-Fa-Mi-Fa-Mi-Re-Do" },
        { time: "6:30", text: "[Sings So-La-So-Fa-Mi-Fa-Mi-Re-Do]", translation: "[唱So-La-So-Fa-Mi-Fa-Mi-Re-Do]" },
        { time: "6:40", text: "Many songs share the same melodic DNA.", translation: "好多歌分享相同旋律DNA" },
        { time: "6:45", text: "For example, the Do-Re-Mi-So pattern appears in", translation: "例如，Do-Re-Mi-So模式出現喺" },
        { time: "6:50", text: "Beyonce songs, The Greatest Showman, and many others.", translation: "Beyonce歌、The Greatest Showman，同好多其他" },
        { time: "6:55", text: "The more you practice these chunks,", translation: "你越練習呢啲片段" },
        { time: "7:00", text: "the better you'll recognize patterns in real songs.", translation: "你會越容易認出真實歌曲中嘅模式" },
        { time: "7:05", text: "The third approach is guessing, but within a scale.", translation: "第三個方法係猜測，但係喺音階內" },
        { time: "7:10", text: "You must guess at the piano,", translation: "你一定要喺鋼琴猜測" },
        { time: "7:15", text: "but always guess within the correct scale.", translation: "但永遠喺正確音階內猜測" },
        { time: "7:20", text: "Your progress will go from 10% knowledge and 90% guessing,", translation: "你嘅進步會由10%知識同90%猜測" },
        { time: "7:25", text: "to 50/50,", translation: "去到50/50" },
        { time: "7:30", text: "to eventually 95% knowledge and only 5% guessing.", translation: "最終去到95%知識同只係5%猜測" },
        { time: "7:35", text: "The scale formula is: Whole-Whole-Half-Whole-Whole-Whole-Half.", translation: "音階公式係：全-全-半-全-全-全-半" },
        { time: "7:40", text: "You might be able to hear 'Do-Re-Mi-Fa-So-Fa-Mi',", translation: "你可能聽到'Do-Re-Mi-Fa-So-Fa-Mi'" },
        { time: "7:45", text: "but you must find the correct key or scale first.", translation: "但你要先搵到正確調或音階" },
        { time: "7:50", text: "Now let's talk about Phase IV: Training Chords.", translation: "而家我哋講第四階段：訓練和弦" },
        { time: "7:55", text: "The most common chords in music are I, IV, V, and vi.", translation: "音樂中最常見嘅和弦係I、IV、V、vi" },
        { time: "8:00", text: "These four chords make up about 80% of all music.", translation: "呢四個和弦組成大約80%所有音樂" },
        { time: "8:05", text: "So start with these four before learning the others.", translation: "所以先學呢四個，再學其他" },
        { time: "8:10", text: "Let me explain the characteristics of each chord.", translation: "等我解釋每個和弦嘅特徵" },
        { time: "8:15", text: "The I chord, or the one chord,", translation: "I和弦，或者一級和弦" },
        { time: "8:20", text: "sounds resolved, stable, like home base.", translation: "聽起上嚟解決咗、穩定，好似基地" },
        { time: "8:25", text: "A song can end here and it sounds complete.", translation: "首歌可以喺度結束，聽起上嚟完整" },
        { time: "8:30", text: "[Plays I chord]", translation: "[彈I和弦]" },
        { time: "8:35", text: "The vi chord, or the six chord,", translation: "vi和弦，或者六級和弦" },
        { time: "8:40", text: "sounds sad, somber, depressing.", translation: "聽起上嚟傷心、憂鬱、壓抑" },
        { time: "8:45", text: "[Plays vi chord]", translation: "[彈vi和弦]" },
        { time: "8:50", text: "The V chord, or the five chord,", translation: "V和弦，或者五級和弦" },
        { time: "8:55", text: "sounds unresolved, wants to move.", translation: "聽起上嚟未解決，想移動" },
        { time: "9:00", text: "It's the polar opposite of the I chord.", translation: "係I和弦完全相反" },
        { time: "9:05", text: "It creates tension that wants to release.", translation: "佢製造想釋放嘅張力" },
        { time: "9:10", text: "[Plays V chord]", translation: "[彈V和弦]" },
        { time: "9:15", text: "The IV chord, or the four chord,", translation: "IV和弦，或者四級和弦" },
        { time: "9:20", text: "sounds peaceful, somewhat resolved but not as stable as I.", translation: "聽起上嚟平靜，有啲解決但冇I咁穩定" },
        { time: "9:25", text: "[Plays IV chord]", translation: "[彈IV和弦]" },
        { time: "9:30", text: "Now let me mention the other chords briefly.", translation: "而家我簡短提下其他和弦" },
        { time: "9:35", text: "The ii chord, or the two chord,", translation: "ii和弦，或者二級和弦" },
        { time: "9:40", text: "is a 'bridge chord' - surprising, jumps out.", translation: "係'橋樑和弦' - 令人驚訝，突出" },
        { time: "9:45", text: "It can sound happy or sad depending on context.", translation: "可以聽起上嚟開心或傷心，視乎情況" },
        { time: "9:50", text: "The iii chord, or the three chord,", translation: "iii和弦，或者三級和弦" },
        { time: "9:55", text: "sounds melancholy, hauntingly beautiful, sad but less stable than vi.", translation: "聽起上嚟憂鬱、淒美，傷心但冇vi咁穩定" },
        { time: "10:00", text: "It wants to lead elsewhere.", translation: "佢想引導去其他地方" },
        { time: "10:05", text: "The vii chord, or the seven chord,", translation: "vii和弦，或者七級和弦" },
        { time: "10:10", text: "is rarely used in modern music because it's too dissonant.", translation: "現代音樂好少用，因為太不和諧" },
        { time: "10:15", text: "Usually it appears as a V chord with a 7 in the bass.", translation: "通常以V和弦形式出現，低音係7" },
        { time: "10:20", text: "Now, how do you train to recognize these chords?", translation: "而家，點樣訓練識別呢啲和弦？" },
        { time: "10:25", text: "There are a few methods.", translation: "有幾個方法" },
        { time: "10:30", text: "First, emotional recognition: listen for how each chord feels.", translation: "首先，情感識別：聽每個和弦嘅感覺" },
        { time: "10:35", text: "Second, the bass line method:", translation: "第二，低音線方法：" },
        { time: "10:40", text: "hum the lowest bass note of each chord,", translation: "哼每個和弦最低低音" },
        { time: "10:45", text: "then build the chord from that root.", translation: "然後由個根音建立和弦" },
        { time: "10:50", text: "And these emotional qualities work across instruments:", translation: "呢啲情感特質適用於所有樂器：" },
        { time: "10:55", text: "piano, guitar, synth - they all have the same feeling.", translation: "鋼琴、結他、合成器 - 佢哋都有相同感覺" },
        { time: "11:00", text: "Let's move to Phase V: Finding The Key.", translation: "我哋去第五階段：搵調" },
        { time: "11:05", text: "First, let's talk about relative pitch versus perfect pitch.", translation: "首先，我哋講下相對音感對絕對音感" },
        { time: "11:10", text: "You don't need perfect pitch to play by ear.", translation: "你唔需要絕對音感先可以靠聽力彈" },
        { time: "11:15", text: "Relative pitch is sufficient.", translation: "相對音感就夠" },
        { time: "11:20", text: "Your ear cares about relationships between notes, not absolute pitches.", translation: "你隻耳關心音之間嘅關係，唔係絕對音高" },
        { time: "11:25", text: "Do-Re-Mi sounds the same regardless of what key you're in.", translation: "Do-Re-Mi聽起上嚟一樣，無論你喺咩調" },
        { time: "11:30", text: "The I chord sounds like home base in any key.", translation: "I和弦喺任何調都聽起上嚟好似基地" },
        { time: "11:35", text: "So how do you find the key?", translation: "所以點樣搵調？" },
        { time: "11:40", text: "The first method is to hum the root note.", translation: "第一個方法係哼根音" },
        { time: "11:45", text: "Let it come from your voice and ear,", translation: "由你聲音同耳嚟" },
        { time: "11:50", text: "don't just noodle around on the piano randomly.", translation: "唔好只係喺鋼琴亂彈" },
        { time: "11:55", text: "The second method is the Pivot Test.", translation: "第二個方法係樞軸測試" },
        { time: "12:00", text: "Hum your suspected root, then pivot down Do-Ti-Do.", translation: "哼你懷疑嘅根音，然後樞軸向下Do-Ti-Do" },
        { time: "12:05", text: "That's going down a half step and back.", translation: "就係向下半音然後返嚟" },
        { time: "12:10", text: "If you're correct, it sounds good against the song.", translation: "如果你啱，對首歌聽起上嚟好" },
        { time: "12:15", text: "If you're wrong, it sounds dissonant or wrong.", translation: "如果你錯，聽起上嚟不和諧或錯" },
        { time: "12:20", text: "An alternative is to Google the key,", translation: "另一個方法係Google個調" },
        { time: "12:25", text: "but I don't recommend this because", translation: "但我唔建議，因為" },
        { time: "12:30", text: "it relies on others' potentially wrong information.", translation: "依賴其他人可能錯嘅資料" },
        { time: "12:35", text: "Once you've found the key,", translation: "一旦你搵到調" },
        { time: "12:40", text: "use the scale formula: Whole-Whole-Half-Whole-Whole-Whole-Half.", translation: "用音階公式：全-全-半-全-全-全-半" },
        { time: "12:45", text: "Apply this to both melody AND chords.", translation: "應用喺旋律同和弦" },
        { time: "12:50", text: "Remember which notes belong in your scale.", translation: "記住邊啲音屬於你音階" },
        { time: "12:55", text: "For example, F major has B-flat.", translation: "例如，F大調有B♭" },
        { time: "13:00", text: "You need to remember this for both melodies and chord building.", translation: "你需要記住，對旋律同建立和弦都係" },
        { time: "13:05", text: "Now let's put it all together in Phase VI.", translation: "而家我哋喺第六階段將所有嘢組合" },
        { time: "13:10", text: "Let me walk you through a live example.", translation: "等我帶你睇一個實例" },
        { time: "13:15", text: "First, I'll listen and identify the chord sounds.", translation: "首先，我會聽同識別和弦聲音" },
        { time: "13:20", text: "I hear an I chord, then a IV chord.", translation: "我聽到I和弦，然後IV和弦" },
        { time: "13:25", text: "Then I identify the melody pattern.", translation: "然後我識別旋律模式" },
        { time: "13:30", text: "For example, Fa-Mi-Re-Do, Fa-Mi-Re-Do.", translation: "例如，Fa-Mi-Re-Do、Fa-Mi-Re-Do" },
        { time: "13:35", text: "Next, I find the key by testing on the piano.", translation: "下一步，我喺鋼琴測試搵調" },
        { time: "13:40", text: "I'll try C, then C#, and so on.", translation: "我會試C，然後C#，如此類推" },
        { time: "13:45", text: "Once I find it, I apply everything to that key.", translation: "一旦搵到，我將所有嘢應用落去個調" },
        { time: "13:50", text: "Then I play and verify it matches.", translation: "然後我彈同驗證配對" },
        { time: "13:55", text: "The key insight is this:", translation: "關鍵洞察係：" },
        { time: "14:00", text: "Once you're trained, this process happens mentally.", translation: "一旦你訓練好，呢個過程會喺腦中發生" },
        { time: "14:05", text: "You learn the melody, learn the chord sounds,", translation: "你學旋律，學和弦聲音" },
        { time: "14:10", text: "then apply it to the correct scale.", translation: "然後應用落去正確音階" },
        { time: "14:15", text: "It takes work and time, but it becomes intuitive.", translation: "需要工作同時間，但會變得直覺" },
        { time: "14:20", text: "A few additional tips:", translation: "幾個額外提示：" },
        { time: "14:25", text: "Chords have the same emotional qualities across different instruments.", translation: "和弦喺唔同樂器有相同情感特質" },
        { time: "14:30", text: "Your progress will start with mostly guessing,", translation: "你嘅進步會由大部分猜測開始" },
        { time: "14:35", text: "and gradually reduce guesswork as you internalize.", translation: "逐漸減少猜測，當你內化時" },
        { time: "14:40", text: "Focus on I, IV, V, and vi chords first - that's 80% of music.", translation: "先專注I、IV、V、vi和弦 - 就係80%音樂" },
        { time: "14:45", text: "The progression I-V-vi-IV appears in hundreds of songs.", translation: "I-V-vi-IV進行出現喺數百首歌" },
        { time: "14:50", text: "Practice recognizing this pattern.", translation: "練習識別呢個模式" },
        { time: "14:55", text: "That's it for this comprehensive guide.", translation: "就係呢個全面指南" },
        { time: "15:00", text: "Remember: music is simpler than you think.", translation: "記住：音樂比你以為嘅簡單" },
        { time: "15:05", text: "Just 14 sounds to learn, and with practice,", translation: "只係14個聲音要學，同練習" },
        { time: "15:10", text: "you'll be able to play any song by ear.", translation: "你會能夠靠聽力彈任何歌" },
        { time: "15:15", text: "Thanks for watching, and happy practicing!", translation: "多謝收睇，練習愉快！" },
        { time: "15:20", text: "[Music]", translation: "[音樂]" },
        { time: "15:25", text: "Before we wrap up, let me give you some practical examples", translation: "結束前，等我俾你啲實用例子" },
        { time: "15:30", text: "to really solidify these concepts.", translation: "真正鞏固呢啲概念" },
        { time: "15:35", text: "Let's practice identifying chords in a real song.", translation: "我哋練習識別真實歌曲中嘅和弦" },
        { time: "15:40", text: "[Plays a chord progression]", translation: "[彈和弦進行]" },
        { time: "15:45", text: "What did you hear there?", translation: "你聽到咩？" },
        { time: "15:50", text: "That was I-V-vi-IV, one of the most common progressions.", translation: "就係I-V-vi-IV，最常見進行之一" },
        { time: "15:55", text: "You'll hear this in songs like 'Let It Be', 'No Woman No Cry',", translation: "你會喺'Let It Be'、'No Woman No Cry'" },
        { time: "16:00", text: "'Don't Stop Believin'', and hundreds of others.", translation: "'Don't Stop Believin''，同數百首其他歌聽到" },
        { time: "16:05", text: "Once you recognize this pattern,", translation: "一旦你識別呢個模式" },
        { time: "16:10", text: "you'll start hearing it everywhere.", translation: "你會開始到處都聽到" },
        { time: "16:15", text: "Now let's practice some melody chunks.", translation: "而家我哋練習啲旋律片段" },
        { time: "16:20", text: "Try to sing this after me:", translation: "試下跟我唱：" },
        { time: "16:25", text: "[Sings Do-Re-Mi-Fa-So]", translation: "[唱Do-Re-Mi-Fa-So]" },
        { time: "16:30", text: "Now try it without the piano.", translation: "而家試下冇鋼琴" },
        { time: "16:35", text: "Just from memory.", translation: "只係靠記憶" },
        { time: "16:40", text: "That's the goal - to internalize these patterns.", translation: "就係目標 - 內化呢啲模式" },
        { time: "16:45", text: "Let me show you another common pattern:", translation: "等我示範另一個常見模式：" },
        { time: "16:50", text: "[Sings So-La-So-Fa-Mi-Re-Do]", translation: "[唱So-La-So-Fa-Mi-Re-Do]" },
        { time: "16:55", text: "This pattern appears in countless songs.", translation: "呢個模式出現喺無數首歌" },
        { time: "17:00", text: "Practice singing this until you can do it acapella.", translation: "練習唱直到你可以無伴奏做到" },
        { time: "17:05", text: "Then check yourself with the piano.", translation: "然後用鋼琴檢查自己" },
        { time: "17:10", text: "Now, let's talk about common mistakes.", translation: "而家，我哋講下常見錯誤" },
        { time: "17:15", text: "One mistake I see a lot is people trying to learn everything at once.", translation: "我見到好多人犯嘅錯誤係想一次學晒所有嘢" },
        { time: "17:20", text: "Don't do that.", translation: "唔好咁做" },
        { time: "17:25", text: "Focus on one thing at a time.", translation: "一次專注一樣嘢" },
        { time: "17:30", text: "Master the I, IV, V, and vi chords first.", translation: "先掌握I、IV、V、vi和弦" },
        { time: "17:35", text: "Then move on to the others.", translation: "然後再去其他" },
        { time: "17:40", text: "Another mistake is not singing.", translation: "另一個錯誤係唔唱" },
        { time: "17:45", text: "You must sing to train your ear.", translation: "你一定要唱先可以訓練隻耳" },
        { time: "17:50", text: "Even if you think you can't sing,", translation: "就算你覺得你唱唔到" },
        { time: "17:55", text: "you need to do it.", translation: "你都需要做" },
        { time: "18:00", text: "The act of singing connects your ear to your voice,", translation: "唱嘅動作連接你隻耳到你聲音" },
        { time: "18:05", text: "which is essential for ear training.", translation: "對聽力訓練好重要" },
        { time: "18:10", text: "A third mistake is giving up too early.", translation: "第三個錯誤係太早放棄" },
        { time: "18:15", text: "This takes time and practice.", translation: "呢個需要時間同練習" },
        { time: "18:20", text: "You won't be able to play everything by ear after one day.", translation: "你唔會一日之後就靠聽力彈到所有嘢" },
        { time: "18:25", text: "But if you stick with it,", translation: "但如果你堅持" },
        { time: "18:30", text: "you'll see progress week by week.", translation: "你會每星期見到進步" },
        { time: "18:35", text: "Let me answer some common questions.", translation: "等我答幾個常見問題" },
        { time: "18:40", text: "Question one: Do I need perfect pitch?", translation: "問題一：我需要絕對音感嗎？" },
        { time: "18:45", text: "No, you absolutely do not.", translation: "唔需要，絕對唔需要" },
        { time: "18:50", text: "Relative pitch is all you need.", translation: "相對音感就夠" },
        { time: "18:55", text: "Perfect pitch is rare and not necessary.", translation: "絕對音感好罕有，唔係必要" },
        { time: "19:00", text: "Question two: How long will this take?", translation: "問題二：要幾耐？" },
        { time: "19:05", text: "It depends on how much you practice.", translation: "視乎你練習幾多" },
        { time: "19:10", text: "If you practice daily for 15-30 minutes,", translation: "如果你每日練習15-30分鐘" },
        { time: "19:15", text: "you'll see significant progress in a few months.", translation: "幾個月內你會見到明顯進步" },
        { time: "19:20", text: "But remember, this is a lifelong skill.", translation: "但記住，呢個係終身技能" },
        { time: "19:25", text: "Even professional musicians keep practicing.", translation: "就算專業音樂人都繼續練習" },
        { time: "19:30", text: "Question three: Can I skip the singing part?", translation: "問題三：我可以跳過唱嘅部分嗎？" },
        { time: "19:35", text: "No, you really can't.", translation: "唔可以，真係唔可以" },
        { time: "19:40", text: "Singing is crucial for ear training.", translation: "唱對聽力訓練好重要" },
        { time: "19:45", text: "It's how you internalize the sounds.", translation: "就係你內化聲音嘅方法" },
        { time: "19:50", text: "Even if you're not a good singer,", translation: "就算你唱得唔好" },
        { time: "19:55", text: "the act of trying to sing helps your ear.", translation: "嘗試唱嘅動作會幫到你隻耳" },
        { time: "20:00", text: "Question four: What if I make mistakes?", translation: "問題四：如果我犯錯點算？" },
        { time: "20:05", text: "Mistakes are part of learning.", translation: "錯誤係學習一部分" },
        { time: "20:10", text: "Don't be afraid to make them.", translation: "唔好怕犯錯" },
        { time: "20:15", text: "Every mistake teaches you something.", translation: "每個錯誤都教到你嘢" },
        { time: "20:20", text: "The key is to learn from them.", translation: "關鍵係從中學習" },
        { time: "20:25", text: "Now let's do a quick review.", translation: "而家我哋做個快速回顧" },
        { time: "20:30", text: "Remember: music has only 14 sounds.", translation: "記住：音樂只有14個聲音" },
        { time: "20:35", text: "Seven melody notes and seven chords.", translation: "七個旋律音同七個和弦" },
        { time: "20:40", text: "Songs are melody plus chords.", translation: "歌係旋律加和弦" },
        { time: "20:45", text: "Train them separately.", translation: "分開訓練" },
        { time: "20:50", text: "For melodies, practice intervals, chunks, and guessing within scales.", translation: "對旋律，練習音程、片段、同音階內猜測" },
        { time: "20:55", text: "For chords, start with I, IV, V, and vi.", translation: "對和弦，由I、IV、V、vi開始" },
        { time: "21:00", text: "Learn their emotional qualities.", translation: "學佢哋嘅情感特質" },
        { time: "21:05", text: "To find the key, hum the root and use the pivot test.", translation: "搵調，哼根音同用樞軸測試" },
        { time: "21:10", text: "Use the scale formula: Whole-Whole-Half-Whole-Whole-Whole-Half.", translation: "用音階公式：全-全-半-全-全-全-半" },
        { time: "21:15", text: "Most importantly, practice consistently.", translation: "最重要，持續練習" },
        { time: "21:20", text: "A little bit every day is better than a lot once a week.", translation: "每日少少好過每星期一次好多" },
        { time: "21:25", text: "Let me give you a practice schedule suggestion.", translation: "等我俾你一個練習時間表建議" },
        { time: "21:30", text: "Week 1-2: Focus on learning the I, IV, V, and vi chords.", translation: "第1-2週：專注學I、IV、V、vi和弦" },
        { time: "21:35", text: "Spend 10 minutes a day just listening to these chords.", translation: "每日用10分鐘只係聽呢啲和弦" },
        { time: "21:40", text: "Try to identify them in songs you know.", translation: "試下喺你識嘅歌識別佢哋" },
        { time: "21:45", text: "Week 3-4: Add melody interval training.", translation: "第3-4週：加入旋律音程訓練" },
        { time: "21:50", text: "Practice singing intervals acapella.", translation: "練習無伴奏唱音程" },
        { time: "21:55", text: "Start with seconds and thirds, then move to larger intervals.", translation: "由二度同三度開始，然後去更大音程" },
        { time: "22:00", text: "Week 5-6: Focus on melody chunks.", translation: "第5-6週：專注旋律片段" },
        { time: "22:05", text: "This is where you'll spend most of your time long-term.", translation: "呢度係你長期會用大部分時間嘅地方" },
        { time: "22:10", text: "Practice different note combinations.", translation: "練習唔同音組合" },
        { time: "22:15", text: "Week 7-8: Practice finding keys.", translation: "第7-8週：練習搵調" },
        { time: "22:20", text: "Pick simple songs and try to find their keys.", translation: "揀簡單歌，試搵佢哋嘅調" },
        { time: "22:25", text: "Use the pivot test to verify.", translation: "用樞軸測試驗證" },
        { time: "22:30", text: "After that, it's all about putting it together", translation: "之後，就係將所有嘢組合" },
        { time: "22:35", text: "and practicing with real songs.", translation: "同用真實歌曲練習" },
        { time: "22:40", text: "One final tip: record your progress.", translation: "最後一個提示：記錄你嘅進步" },
        { time: "22:45", text: "Try to figure out a song today,", translation: "今日試搵首歌" },
        { time: "22:50", text: "then try the same song again in a month.", translation: "然後一個月後再試同一首歌" },
        { time: "22:55", text: "You'll be amazed at how much easier it gets.", translation: "你會驚訝變得幾容易" },
        { time: "23:00", text: "That's a great way to see your improvement.", translation: "係一個好方法見到你嘅進步" },
        { time: "23:05", text: "I want to emphasize one more time:", translation: "我想再強調一次：" },
        { time: "23:10", text: "this is achievable for everyone.", translation: "呢個對每個人都有可能" },
        { time: "23:15", text: "You don't need special talent.", translation: "你唔需要特殊天賦" },
        { time: "23:20", text: "You just need consistent practice.", translation: "你只需要持續練習" },
        { time: "23:25", text: "Start small, be patient, and trust the process.", translation: "由小開始，有耐心，相信過程" },
        { time: "23:30", text: "Before we finish, let me play you one more example.", translation: "結束前，等我彈多一個例子俾你" },
        { time: "23:35", text: "[Plays a complete song excerpt]", translation: "[彈完整首歌片段]" },
        { time: "23:50", text: "Can you hear the I-V-vi-IV progression?", translation: "你聽到I-V-vi-IV進行嗎？" },
        { time: "23:55", text: "Can you hear the melody pattern?", translation: "你聽到旋律模式嗎？" },
        { time: "24:00", text: "With practice, you'll be able to identify these instantly.", translation: "通過練習，你會能夠即時識別呢啲" },
        { time: "24:05", text: "And then you'll be able to play any song by ear.", translation: "然後你會能夠靠聽力彈任何歌" },
        { time: "24:10", text: "That's the goal we're working towards.", translation: "就係我哋努力嘅目標" },
        { time: "24:15", text: "Thank you so much for watching this comprehensive guide.", translation: "多謝你收睇呢個全面指南" },
        { time: "24:20", text: "I hope this has been helpful.", translation: "我希望呢個幫到你" },
        { time: "24:25", text: "Remember: music is simpler than you think,", translation: "記住：音樂比你以為嘅簡單" },
        { time: "24:30", text: "and with practice, you can master it.", translation: "同練習，你可以掌握佢" },
        { time: "24:35", text: "If you have questions, leave them in the comments below.", translation: "如果你有問題，下面留言" },
        { time: "24:40", text: "I'll do my best to answer them.", translation: "我會盡力答" },
        { time: "24:45", text: "Don't forget to like and subscribe", translation: "記得讚好同訂閱" },
        { time: "24:50", text: "if you found this helpful.", translation: "如果你覺得有用" },
        { time: "24:55", text: "And most importantly, happy practicing!", translation: "最重要，練習愉快！" },
        { time: "24:32", text: "Okay we've talked about the seven melody notes we've talked about the seven chords", translation: "好，我哋講咗七個旋律音，講咗七個和弦" },
        { time: "24:39", text: "but at this point you might notice if you're really observant or you know about music theory", translation: "但而家你可能會注意到，如果你真係觀察力強或識音樂理論" },
        { time: "24:45", text: "that there's a huge problem that we haven't covered yet", translation: "有個大問題我哋未講" },
        { time: "24:49", text: "and I put problem in scare quotes because it's not actually an issue", translation: "我將問題加引號，因為其實唔係問題" },
        { time: "24:52", text: "but basically everything we've done to this point has been in the key of C", translation: "但基本上我哋做到而家都係C調" },
        { time: "24:59", text: "and the thing is there's other scales out there there's D major and G major and F sharp", translation: "問題係有其他音階，有D大調、G大調、F#大調" },
        { time: "25:04", text: "all these other scales but the good news here's what's awesome", translation: "所有呢啲其他音階，但好消息係好正嘅係" },
        { time: "25:11", text: "everything that we've learned applies to all of those other scales in the exact same way", translation: "我哋學到嘅所有嘢都適用於所有其他音階，完全一樣" },
        { time: "25:17", text: "all we have to do is figure out what specific scale a song is using", translation: "我哋只需要搵到首歌用緊咩特定音階" },
        { time: "25:24", text: "and let me illustrate what I'm talking about a little bit", translation: "等我示範下我講緊咩" },
        { time: "25:31", text: "so basically what I'm trying to say is Do Re Mi is going to sound the same", translation: "基本上我想講嘅係Do Re Mi會聽起上嚟一樣" },
        { time: "25:36", text: "regardless of what scale you're using", translation: "無論你用咩音階" },
        { time: "25:40", text: "the one chord is going to sound like your home base", translation: "一級和弦會聽起上嚟好似你基地" },
        { time: "25:45", text: "the six chord is going to sound sad no matter what scale you're using", translation: "六級和弦會聽起上嚟傷心，無論你用咩音階" },
        { time: "25:52", text: "everything we talked about still applies", translation: "我哋講過嘅所有嘢仍然適用" },
        { time: "25:56", text: "so let me prove that to you", translation: "等我證明俾你睇" },
        { time: "26:04", text: "let's say I'm trying to sing Journey okay and I'm trying to do Don't Stop Believin'", translation: "假設我試唱Journey，試唱Don't Stop Believin'" },
        { time: "26:10", text: "just a small town girl okay that's really high I'm not Steve Perry", translation: "just a small town girl，好高音，我唔係Steve Perry" },
        { time: "26:16", text: "so let's lower that down and let's change keys", translation: "所以降低佢，轉調" },
        { time: "26:23", text: "okay so let's say I'm moving it from the key of E the original scale", translation: "假設我由E調（原調）移動" },
        { time: "26:30", text: "and now I'm going to move it down like six notes let's do the key of G", translation: "而家我降低大約六個音，用G調" },
        { time: "26:36", text: "and watch this it's still gonna sound like Don't Stop Believin'", translation: "睇下，仍然會聽起上嚟好似Don't Stop Believin'" },
        { time: "26:42", text: "she's just a small town girl living in a lonely world", translation: "she's just a small town girl living in a lonely world" },
        { time: "26:50", text: "something like that but why did that still sound like Don't Stop Believin'?", translation: "類似咁，但點解仍然聽起上嚟好似Don't Stop Believin'？" },
        { time: "26:56", text: "I changed every melody note I changed every chord", translation: "我改咗每個旋律音，改咗每個和弦" },
        { time: "27:01", text: "why doesn't it sound like a totally different song?", translation: "點解唔會聽起上嚟完全唔同嘅歌？" },
        { time: "27:07", text: "well the reason is our ear unless you have perfect pitch", translation: "原因係我哋隻耳，除非你有絕對音感" },
        { time: "27:13", text: "doesn't super care about what scale a song is using", translation: "唔太關心首歌用緊咩音階" },
        { time: "27:18", text: "and it cares way more about the relationships between the notes", translation: "佢更關心音之間嘅關係" },
        { time: "27:23", text: "we call this relative pitch", translation: "我哋叫呢個相對音感" },
        { time: "27:27", text: "so even if you don't have perfect pitch which I don't have", translation: "所以就算你冇絕對音感（我冇）" },
        { time: "27:32", text: "I can't just listen to a note and say well that's E sharp", translation: "我唔可以只係聽個音就話係E#" },
        { time: "27:37", text: "even if you don't have that you can hear the Do Re Mi's", translation: "就算你冇，你可以聽到Do Re Mi" },
        { time: "27:42", text: "you can hear the one chord the IV chord", translation: "你可以聽到一級和弦、IV和弦" },
        { time: "27:47", text: "you can hear all the music theory underneath it", translation: "你可以聽到下面所有音樂理論" },
        { time: "27:52", text: "and then go apply it on the piano or the guitar or whatever your instrument is", translation: "然後應用落鋼琴或結他或任何你嘅樂器" },
        { time: "27:58", text: "all right now I know that's a little weird to wrap your head around", translation: "好，我知道有啲難理解" },
        { time: "28:03", text: "so let's do one more thing here that I think is going to make it make sense for you", translation: "所以我哋再做一件事，我覺得會令你明白" },
        { time: "28:09", text: "we're going to listen to a little bit of Ed Sheeran real quick", translation: "我哋會快速聽下Ed Sheeran" },
        { time: "28:15", text: "[Music]", translation: "[音樂]" },
        { time: "28:20", text: "now I don't have perfect pitch so if I just heard that", translation: "而家我冇絕對音感，所以如果我只係聽到" },
        { time: "28:25", text: "I have no idea like what exact key this is in", translation: "我完全唔知係咩調" },
        { time: "28:30", text: "but I do know that I heard I'm on my way Do Re Mi Mi", translation: "但我確實知道聽到I'm on my way Do Re Mi Mi" },
        { time: "28:36", text: "I know that's Do Re Mi Mi", translation: "我知道係Do Re Mi Mi" },
        { time: "28:40", text: "so all I have to do is go to the piano and figure out what scale Ed Sheeran's", translation: "所以我只需要去鋼琴，搵Ed Sheeran" },
        { time: "28:46", text: "using for this song is it in the C scale the D scale", translation: "首歌用緊咩音階，係C音階定D音階" },
        { time: "28:51", text: "that's the part that we have to figure out", translation: "呢個係我哋要搵嘅部分" },
        { time: "28:55", text: "but let's see so no there we go there's Do", translation: "但睇下，唔係，就係呢度，係Do" },
        { time: "29:01", text: "I'm on my way so now I can take everything I just heard", translation: "I'm on my way，而家我可以攞所有我剛聽到嘅" },
        { time: "29:07", text: "and I can play the song", translation: "然後我可以彈首歌" },
        { time: "29:12", text: "[Music]", translation: "[音樂]" },
        { time: "29:18", text: "so I listened to it I figured out what the melody was doing", translation: "所以我聽咗，搵到旋律做緊咩" },
        { time: "29:23", text: "and then I just plugged it in I mapped it out to the key that the song is in", translation: "然後我插入去，映射到首歌嘅調" },
        { time: "29:29", text: "in this case the key of D", translation: "呢個情況係D調" },
        { time: "29:32", text: "now that begs the question well how do we figure out the key of our song?", translation: "而家問題係點樣搵首歌嘅調？" },
        { time: "29:38", text: "maybe I can hear Do Re Mi maybe I can hear the one chord", translation: "可能我聽到Do Re Mi，可能我聽到一級和弦" },
        { time: "29:43", text: "but how on earth do I figure out what scale the song is in?", translation: "但我點樣搵到首歌用緊咩音階？" },
        { time: "29:49", text: "well the answer is really easy all we're going to try to do", translation: "答案好簡單，我哋只係試做" },
        { time: "29:54", text: "is find the root note the home base note", translation: "搵根音，基地音" },
        { time: "29:59", text: "and what I do is I tell my students to just try and hum it", translation: "我做嘅係話俾學生知試下哼佢" },
        { time: "30:04", text: "let it come from your voice let it come from your ear", translation: "由你聲音嚟，由你隻耳嚟" },
        { time: "30:09", text: "don't try to just noodle around on a piano or a guitar", translation: "唔好只係喺鋼琴或結他亂彈" },
        { time: "30:14", text: "so let's pick another song for example let's say we're listening to Fun", translation: "所以我哋揀另一首歌，例如我哋聽緊Fun" },
        { time: "30:22", text: "[Music]", translation: "[音樂]" },
        { time: "30:27", text: "okay so I'm gonna try and hum", translation: "好，我會試哼" },
        { time: "30:32", text: "[Music]", translation: "[音樂]" },
        { time: "30:37", text: "so it took me a second there", translation: "用咗我一秒" },
        { time: "30:42", text: "[Music]", translation: "[音樂]" },
        { time: "30:47", text: "that song's in the key of F", translation: "首歌係F調" },
        { time: "30:50", text: "so there's a little bit of that guesswork and just trying to figure out", translation: "所以有少少猜測，只係試搵" },
        { time: "30:55", text: "where that home note is", translation: "基地音喺邊" },
        { time: "30:58", text: "and there's actually a way to check if you've got the right note for your key", translation: "其實有方法檢查你係咪搵到正確音" },
        { time: "31:04", text: "so what some people will do is they'll hum a note that's in the scale", translation: "有啲人會做嘅係哼一個音階內嘅音" },
        { time: "31:09", text: "but maybe it's not the root note maybe it's So", translation: "但可能唔係根音，可能係So" },
        { time: "31:14", text: "right like doing Mi Fa So and you're humming that", translation: "對，好似做Mi Fa So，你哼緊" },
        { time: "31:19", text: "and that's not quite the root note", translation: "但唔係根音" },
        { time: "31:22", text: "but there's a way to check to make sure you're actually on the root", translation: "但有方法檢查確保你真係喺根音" },
        { time: "31:27", text: "and it's called the pivot test", translation: "叫樞軸測試" },
        { time: "31:31", text: "so what you want to do is pivot down Do-Ti-Do down a half step", translation: "所以你想做嘅係樞軸向下Do-Ti-Do，向下半音" },
        { time: "31:37", text: "Do-Ti-Do and it should still sound good as you listen to your song", translation: "Do-Ti-Do，對你首歌應該仍然聽起上嚟好" },
        { time: "31:45", text: "[Music]", translation: "[音樂]" },
        { time: "31:51", text: "so that sounds fine Do-Ti-Do", translation: "所以聽起上嚟好，Do-Ti-Do" },
        { time: "31:55", text: "but let's say I was humming the wrong note", translation: "但假設我哼錯音" },
        { time: "31:59", text: "let's say I thought it was in the key of C", translation: "假設我以為係C調" },
        { time: "32:05", text: "[Music]", translation: "[音樂]" },
        { time: "32:10", text: "okay it's still part of the scale maybe I think that's it", translation: "好，仍然係音階一部分，可能我以為係" },
        { time: "32:15", text: "but then I try the pivot test", translation: "但然後我試樞軸測試" },
        { time: "32:19", text: "[Music]", translation: "[音樂]" },
        { time: "32:25", text: "oh gosh you can just hear it's such a wrong note against what's happening", translation: "天啊，你可以聽到對發生緊嘅嘢係錯音" },
        { time: "32:32", text: "[Music]", translation: "[音樂]" },
        { time: "32:37", text: "and one last way you could do it is you could just google it right", translation: "最後一個方法係你可以Google" },
        { time: "32:42", text: "you could type in what key is the song Carry On by Fun in", translation: "你可以打'Carry On by Fun係咩調'" },
        { time: "32:47", text: "I'm not as much a fan of that way of doing it", translation: "我唔太鍾意呢個方法" },
        { time: "32:51", text: "because it relies on google right it relies on the internet", translation: "因為依賴Google，依賴互聯網" },
        { time: "32:56", text: "and sometimes you know other people are wrong they make mistakes", translation: "有時其他人錯，佢哋犯錯" },
        { time: "33:01", text: "there's bad guitar tabs there's just this whole other world out there", translation: "有錯結他譜，有整個其他世界" },
        { time: "33:06", text: "that you don't need if you can sit down and just listen to it", translation: "如果你可以坐低只係聽，你唔需要" },
        { time: "33:11", text: "and know where you're going", translation: "知道你去緊邊" },
        { time: "33:14", text: "and what's cool about that is once we find our home note", translation: "好正嘅係一旦我哋搵到基地音" },
        { time: "33:19", text: "once we find Do that tells us what scale the song is using", translation: "一旦我哋搵到Do，就話我哋知首歌用緊咩音階" },
        { time: "30:26", text: "then from there our melody is going to exist within that framework", translation: "然後我哋旋律會喺呢個框架內存在" },
        { time: "30:32", text: "we're going to have that B-flat that we just saw so as we guess we want to remember that", translation: "我哋會有B♭，正如我哋剛見到，所以我哋猜測時想記住" },
        { time: "30:39", text: "and even more importantly the chords are also going to have that B flat watch this F is now one okay so that's the one chord", translation: "更重要係和弦都會有B♭，睇下，F而家係一，好，就係一級和弦" },
        { time: "30:45", text: "as I go to two I have to remember the B flat so it's the same shape it's still every other note but I have to remember my scale has B flat in it", translation: "當我去二，我要記住B♭，所以係相同形狀，仍然係隔一個音，但我要記住我音階有B♭" },
        { time: "30:52", text: "then I can go to the three chord then the four chord I have that B flat again", translation: "然後我可以去三級和弦，然後四級和弦，我又有B♭" },
        { time: "30:58", text: "so in other words just remember your scale for both the melody", translation: "所以換句話講，只係記住你音階，對旋律" },
        { time: "31:05", text: "and for your chords [Music] okay this is going to be really cool", translation: "同對和弦 [音樂] 好，呢個會好正" },
        { time: "31:10", text: "let's do a live example of how to put this all together because I think it's helpful not just to learn about it but", translation: "我哋做個實例，點樣將所有嘢組合，因為我覺得唔只係學到，而係" },
        { time: "31:15", text: "to see how it's actually done what it looks like so I pulled up a random Taylor Swift song", translation: "見到點樣實際做，係咩樣，所以我拉咗首隨機Taylor Swift歌" },
        { time: "31:21", text: "it's off the Evermore album because I'm not as familiar with that I think I listened to it once when it first came out but yeah let's check this out", translation: "係Evermore專輯，因為我唔太熟，我覺得第一次出時聽過一次，但好，我哋睇下" },
        { time: "31:33", text: "okay so right there the one chord [Music] there's the IV chord", translation: "好，就係呢度，一級和弦 [音樂] 係IV和弦" },
        { time: "31:39", text: "now I don't know what key it's in right I don't know if it's in the key of D or G or A I really don't know", translation: "而家我唔知係咩調，我唔知係D調定G調定A調，我真係唔知" },
        { time: "31:44", text: "so I'm going to have to go to the piano because I don't have perfect pitch and figure out the scale", translation: "所以我需要去鋼琴，因為我冇絕對音感，搵音階" },
        { time: "31:50", text: "[Music] cool the melody just matches that oh", translation: "[音樂] 正，旋律就配到，哦" },
        { time: "31:55", text: "I can hear the one chord I can hear the four chord those are the two chords we're switching back and forth with", translation: "我聽到一級和弦，我聽到四級和弦，就係我哋來回切換嘅兩個和弦" },
        { time: "32:01", text: "one and four and I can hear the melody Fa-Mi-Re-Do Fa-Mi-Re-Do but I don't know what key I'm in so", translation: "一級同四級，我聽到旋律Fa-Mi-Re-Do Fa-Mi-Re-Do，但我唔知我喺咩調，所以" },
        { time: "32:08", text: "I'm gonna go to the piano there we go took two seconds I tried C", translation: "我會去鋼琴，就係呢度，用咗兩秒，我試C" },
        { time: "32:15", text: "that wasn't quite it and I went up to C sharp here and that's the key we're in", translation: "唔係，我上到C#，呢度，就係我哋嘅調" },
        { time: "32:22", text: "Do-Ti right so I'm locked in there now what I can do is I can go", translation: "Do-Ti，對，我鎖定咗，而家我可以做嘅係我可以去" },
        { time: "32:27", text: "one chord oh [Music]", translation: "一級和弦，哦 [音樂]" },
        { time: "32:33", text: "on the four chord there okay so it looks easy right once you've trained all this", translation: "四級和弦，呢度，好，睇起上嚟容易，對，一旦你訓練好所有呢啲" },
        { time: "32:40", text: "it's all happening up here you've learned the melody you've learned the way the chords sound then you just apply it to a certain scale", translation: "全部喺上面發生，你學咗旋律，學咗和弦聽起上嚟係點，然後你只係應用落某個音階" },
        { time: "32:46", text: "looks easy but it does take work and it does take time to train that I didn't hold anything back right I'm not leaving", translation: "睇起上嚟容易，但需要工作同時間訓練，我冇隱藏任何嘢，對，我冇留低" },
        { time: "32:51", text: "out some big secret but of course we need a little bit more guidance for most people to actually take them from point", translation: "大秘密，但當然我哋需要多啲指導，對大部分人，真正由點" },
        { time: "32:57", text: "A to point B and get them applying all this so if you want to learn a little bit more from me you can check out my", translation: "A到點B，同應用所有呢啲，所以如果你想從我學多啲，你可以睇我" },
        { time: "33:03", text: "whole piano by ear course which takes you step by step through exactly how to do this stuff and in the course we go so", translation: "整個靠聽力彈琴課程，會逐步帶你睇點樣做呢啲嘢，課程入面我哋會" },
        { time: "33:10", text: "much more in depth on everything that we've talked about today I get way more into the music theory with the different", translation: "深入好多，對今日講過嘅所有嘢，我會深入好多音樂理論，唔同" },
        { time: "33:15", text: "chords and scales I show you not just the melodies like we did today but we have audio exercises we have interactive", translation: "和弦同音階，我唔只示範旋律，好似今日做，但我哋有音頻練習，有互動" },
        { time: "33:21", text: "things where you're naming certain things and then at the end we have a whole module on how to put it together", translation: "嘢，你命名特定嘢，然後最後我哋有整個模組，點樣組合" },
        { time: "33:26", text: "the timing between the melody and the chords we didn't really cover that today there's so much more to dig into in the", translation: "旋律同和弦之間嘅時機，我哋今日冇真正講，有好多嘢深入" },
        { time: "33:32", text: "full course that I really hope if you're interested in this stuff you give it a chance and you check it out and you can", translation: "完整課程，我真係希望如果你對呢啲嘢有興趣，你俾個機會，睇下，你可以" },
        { time: "33:37", text: "do that using the link below either in the comments or in the description all right so I hope this video was helpful", translation: "用下面連結做，留言或描述入面，好，我希望呢條片幫到你" },
        { time: "33:42", text: "for you I hope it blew your mind and just opened the gates and showed you exactly how this is done and that you", translation: "我希望震撼你，打開大門，示範俾你睇點樣做到，同你" },
        { time: "33:48", text: "take this stuff and you apply it and give yourself an awesome skill that you get to keep for life until next time", translation: "攞呢啲嘢，應用佢，俾自己一個好技能，可以終身擁有，下次見" },
        { time: "33:54", text: "this is Corey Lennox see ya [Music]", translation: "我係Corey Lennox，再見 [音樂]" }
    ],
    summary: {
        corePhilosophy: {
            title: "核心理念",
            text: "音樂是一種語言，但比口語簡單得多。英語有17萬個字，而音樂只需要學大約14個聲音：7個旋律音（Do、Re、Mi、Fa、So、La、Ti）和7個和弦（I、ii、iii、IV、V、vi、vii）。任何歌曲都由兩個部分組成：旋律和和弦。因此，要訓練耳朵，需要分別訓練這兩個領域。"
        },
        phase1: {
            title: "第一階段：音樂語言",
            text: "總共只需要學14個聲音：7個旋律音和7個和弦。這比學習口語簡單得多。七個旋律音是Do、Re、Mi、Fa、So、La、Ti。七個和弦編號為1到7：I、ii、iii、IV、V、vi、vii。這就是音樂的全部語言。"
        },
        phase2: {
            title: "第二階段：音樂理論基礎",
            text: "旋律來自音階，音階就是那七個音：Do-Re-Mi-Fa-So-La-Ti。旋律只是這些音階音的不同組合。℗許多歌曲只使用三個音：Do、Re、Mi，例如Journey的'Don't Stop Believin''、The Chainsmokers的歌曲，或Moana的'How Far I'll Go'。℗和弦也是從音階建立的，使用'隔一個音'的模式。從Do開始，取Do-Mi-So就是I和弦；從Re開始，取Re-Fa-La就是ii和弦。每個音階音都可以變成和弦。"
        },
        phase3: {
            title: "第三階段：訓練旋律（三管齊下）",
            text: "有三個主要方法訓練旋律聽力。℗第一個是音程訓練：音程是音之間的距離（二度、三度等）。方法是唱Do，然後唱音程，再回到Do。關鍵是必須先無伴奏唱，然後用鋼琴檢查自己。目標是無伴奏準確唱每個音程。℗第二個是旋律片段（最重要，花大部分時間）：真實歌曲使用音序列或片段，不只是單一音程。方法是選擇隨機音組合，試著唱出來，然後用鋼琴檢查。許多歌曲分享相同的旋律DNA，例如Do-Re-Mi-So模式出現在Beyonce歌曲、The Greatest Showman等。練習越多，越能識別真實歌曲中的模式。℗第三個是猜測（在音階內）：必須在鋼琴上猜測，但總是在正確音階內猜測。進步會從10%知識/90%猜測，到50/50，最終到95%知識/5%猜測。音階公式是：全-全-半-全-全-全-半。"
        },
        phase4: {
            title: "第四階段：訓練和弦",
            text: "最常見的和弦是I、IV、V、vi，這四個和弦組成約80%的音樂。因此先學這四個，再學其他。℗I和弦（一級）聽起來解決、穩定，像基地，歌曲可以在此結束。vi和弦（六級）聽起來傷心、憂鬱、壓抑。V和弦（五級）聽起來未解決，想移動，是I和弦的完全相反，創造想釋放的張力。IV和弦（四級）聽起來平靜，有些解決但不如I穩定。℗ii和弦（二級）是'橋樑和弦'，令人驚訝，可以聽起來開心或傷心。iii和弦（三級）聽起來憂鬱、淒美，傷心但不如vi穩定，想引導到其他地方。vii和弦（七級）在現代音樂中很少使用，因為太不和諧。℗訓練方法包括：情感識別（聽每個和弦的感覺）、低音線方法（哼每個和弦的最低低音，然後從根音建立和弦）。這些情感特質適用於所有樂器：鋼琴、結他、合成器都有相同感覺。"
        },
        phase5: {
            title: "第五階段：找調",
            text: "不需要絕對音感，相對音感就足夠。耳朵關心音之間的關係，不是絕對音高。Do-Re-Mi在任何調聽起來都一樣，I和弦在任何調都像基地。℗找調的方法：第一個是哼根音，讓它從你的聲音和耳朵來，不要只在鋼琴上隨意彈。第二個是樞軸測試：哼你懷疑的根音，然後樞軸向下Do-Ti-Do（向下半音然後回來）。如果正確，對歌曲聽起來好；如果錯誤，聽起來不和諧或錯。另一個方法是Google調，但不推薦，因為依賴其他人可能錯誤的資訊。℗一旦找到調，使用音階公式：全-全-半-全-全-全-半，應用於旋律和和弦。記住哪些音屬於你的音階（例如F大調有B♭），這對旋律和建立和弦都很重要。"
        },
        phase6: {
            title: "第六階段：整合所有內容",
            text: "實例過程：1) 聽並識別和弦聲音（I和弦、IV和弦）；2) 識別旋律模式（例如Fa-Mi-Re-Do、Fa-Mi-Re-Do）；3) 在鋼琴上測試找調（試C，然後C#等）；4) 將所有內容應用到該調；5) 彈奏並驗證匹配。℗關鍵洞察：一旦訓練好，這個過程會在腦中發生。你學旋律，學和弦聲音，然後應用到正確音階。需要工作和時間，但會變得直覺。℗額外提示：和弦在不同樂器有相同情感特質。進步會從大部分猜測開始，逐漸減少猜測。先專注I、IV、V、vi和弦（80%的音樂）。I-V-vi-IV進行出現在數百首歌中，練習識別這個模式。"
        },
        keyTakeaways: {
            title: "核心要點",
            text: "音樂比你以為的簡單：只需學14個聲音。通過練習，你能夠靠聽力彈任何歌曲。℗重點是先掌握I、IV、V、vi四個和弦，這已涵蓋80%的音樂。旋律訓練最重要的是旋律片段練習，要花大部分時間。℗找調時使用相對音感，不需要絕對音感。整個過程需要時間和練習，但會變得直覺和自動化。"
        },
        commonMistakes: {
            title: "常見錯誤",
            text: "第一個常見錯誤是試圖一次學習所有內容。應該一次專注一件事，先掌握I、IV、V、vi和弦，然後再學習其他。℗第二個錯誤是不唱歌。必須唱歌來訓練耳朵，即使你認為自己不會唱歌。唱歌的動作將耳朵與聲音連接起來，這對聽力訓練至關重要。℗第三個錯誤是過早放棄。這需要時間和練習，你不會在一夜之間就能靠聽力彈奏所有內容，但如果堅持下去，你會每週看到進步。"
        },
        faq: {
            title: "常見問題",
            text: "問題一：需要絕對音感嗎？不需要，絕對不需要。相對音感就足夠了。絕對音感很罕見且不是必需的。℗問題二：需要多長時間？這取決於你練習多少。如果你每天練習15-30分鐘，幾個月內你會看到顯著進步。但記住，這是一項終身技能，即使專業音樂家也會繼續練習。℗問題三：可以跳過唱歌部分嗎？不可以，真的不可以。唱歌對聽力訓練至關重要，這是內化聲音的方式。即使你不是好歌手，嘗試唱歌的動作也會幫助你的耳朵。℗問題四：如果犯錯怎麼辦？錯誤是學習的一部分，不要害怕犯錯。每個錯誤都會教會你一些東西，關鍵是從中學習。"
        },
        practiceSchedule: {
            title: "練習時間表建議",
            text: "第1-2週：專注學習I、IV、V、vi和弦。每天花10分鐘只聽這些和弦，嘗試在你熟悉的歌曲中識別它們。℗第3-4週：加入旋律音程訓練。練習無伴奏唱音程，從二度和三度開始，然後轉向更大的音程。℗第5-6週：專注旋律片段。這是你長期會花大部分時間的地方，練習不同的音組合。℗第7-8週：練習找調。選擇簡單的歌曲並嘗試找到它們的調，使用樞軸測試來驗證。之後，就是將所有內容結合起來，用真實歌曲練習。℗一個額外的提示：記錄你的進步。今天嘗試找出一首歌，然後一個月後再嘗試同一首歌，你會驚訝於它變得有多容易。"
        },
        finalTips: {
            title: "最後提示",
            text: "記住：音樂只有14個聲音 - 七個旋律音和七個和弦。歌曲是旋律加和弦，分開訓練它們。℗對於旋律，練習音程、片段和在音階內猜測。對於和弦，從I、IV、V、vi開始，學習它們的情感特質。要找到調，哼根音並使用樞軸測試。使用音階公式：全-全-半-全-全-全-半。℗最重要的是持續練習。每天一點點比每週一次大量練習更好。℗這對每個人都是可以實現的，你不需要特殊天賦，只需要持續練習。從小開始，保持耐心，相信過程。"
        }
    }
};
