const youtubeExample2Data = {
    videoId: "jtytRXa4epw",
    videoUrl: "https://www.youtube.com/watch?v=jtytRXa4epw",
    embedcode: "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/jtytRXa4epw?si=05u6B9OqkUQJACYs\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>",
    title: "Ear Training Fundamentals",
    cantoneseTitle: "聽力訓練基礎",
    transcript: [
        { time: "0:00", text: "do you want to learn how to play songs", translation: "你想學點樣靠聽力彈歌" },
        { time: "0:01", text: "just by listening to them well a lot of", translation: "就係靠聽，好多人會話" },
        { time: "0:03", text: "people are going to tell you it can't be", translation: "你聽唔到架，或者" },
        { time: "0:04", text: "taught or you've got to be born with", translation: "要天生先得，但係呢啲都" },
        { time: "0:06", text: "perfect pitch and not only is all that", translation: "唔係真架，絕對可以教" },
        { time: "0:08", text: "untrue it definitely can be taught i", translation: "絕對可以教，我想再進一步" },
        { time: "0:11", text: "want to go a step further i'm going to", translation: "我想再進一步，我會" },
        { time: "0:13", text: "make a crazy claim right now that your", translation: "而家講個好誇張嘅講法" },
        { time: "0:15", text: "ear already knows more than you could", translation: "你隻耳已經識得" },
        { time: "0:17", text: "possibly realize", translation: "多過你以為嘅" },
        { time: "0:18", text: "so how can i say that well if we think", translation: "點解我咁講？如果我哋當" },
        { time: "0:21", text: "of music as a language you've been", translation: "音樂係一種語言，你已經" },
        { time: "0:22", text: "exposed to that language your entire", translation: "成世都接觸緊呢種語言" },
        { time: "0:24", text: "life you've been listening to music for", translation: "你聽音樂聽咗好多年" },
        { time: "0:26", text: "years and years so the building blocks", translation: "所以基礎已經喺度" },
        { time: "0:28", text: "are kind of already there whether you", translation: "無論你知唔知道" },
        { time: "0:30", text: "realize it or not so this is going to be", translation: "所以呢個會係" },
        { time: "0:32", text: "a fun video we're going to do some games", translation: "一個好玩嘅片，我哋會做啲遊戲" },
        { time: "0:34", text: "some listening exercises and i really", translation: "同聽力練習，我真係" },
        { time: "0:36", text: "encourage you to make a commitment to", translation: "鼓勵你承諾自己" },
        { time: "0:38", text: "yourself right now to stay through the", translation: "而家要睇完整條片" },
        { time: "0:40", text: "entire video i don't want you to miss", translation: "我唔想你錯過" },
        { time: "0:42", text: "out on anything this is going to be so", translation: "任何嘢，呢個會好" },
        { time: "0:44", text: "eye-opening for you and uh with that", translation: "令你大開眼界，好，就咁" },
        { time: "0:46", text: "said let's get into it now our goal is", translation: "開始，我哋嘅目標係" },
        { time: "0:49", text: "to play songs by ear well what is a song", translation: "靠聽力彈歌，咩係一首歌？" },
        { time: "0:52", text: "there's actually a couple elements to it", translation: "其實有幾個元素" },
        { time: "0:54", text: "a song is a combination of melody and", translation: "一首歌係旋律同" },
        { time: "0:57", text: "chords so any song you could ever want", translation: "和弦嘅組合，所以任何你想彈嘅歌" },
        { time: "0:59", text: "to play is melody with chords beneath it", translation: "都係旋律加下面嘅和弦" },
        { time: "1:02", text: "and you get a song", translation: "就係一首歌" },
        { time: "1:04", text: "so for us to train our ears we have to", translation: "所以我哋要訓練隻耳" },
        { time: "1:06", text: "train those two areas melody and quartz", translation: "就要訓練呢兩個範疇：旋律同和弦" },
        { time: "1:09", text: "here's the good news they both come from", translation: "好消息係佢哋都來自" },
        { time: "1:12", text: "what we call a scale and a scale is", translation: "我哋叫音階，音階係" },
        { time: "1:14", text: "something we've all heard it's that", translation: "我哋都聽過，就係" },
        { time: "1:15", text: "classic", translation: "經典嘅" },
        { time: "1:17", text: "latito", translation: "Do Re Mi Fa So La Ti Do" },
        { time: "1:19", text: "that's a scale", translation: "就係音階" },
        { time: "1:21", text: "and most people know that melody comes", translation: "好多人知道旋律來自" },
        { time: "1:23", text: "from a scale right just different", translation: "音階，就係唔同" },
        { time: "1:24", text: "patterns of those syllables", translation: "音節嘅組合" },
        { time: "1:26", text: "do re mi redo soto", translation: "Do Re Mi Re Do So To" },
        { time: "1:30", text: "that's how we sort of get melodies but", translation: "就係咁樣得到旋律，但係" },
        { time: "1:31", text: "what people don't know is that chords", translation: "好多人唔知嘅係和弦" },
        { time: "1:34", text: "come from the scale too", translation: "都係來自音階" },
        { time: "1:35", text: "so let me show you what i mean", translation: "等我示範俾你睇" },
        { time: "1:37", text: "let's start with something easy say the", translation: "我哋由簡單開始，例如" },
        { time: "1:39", text: "c scale", translation: "C大調音階" },
        { time: "1:40", text: "there we go doh rain me faso la ti do", translation: "就係 Do Re Mi Fa So La Ti Do" },
        { time: "1:44", text: "now let's turn each of these into a", translation: "而家我哋將每個音" },
        { time: "1:46", text: "chord here's what i mean", translation: "變成和弦，就係咁" },
        { time: "1:48", text: "if we take dou as our starting note i'm", translation: "如果我哋用Do做起始音" },
        { time: "1:51", text: "going to do an every other note kind of", translation: "我會隔一個音" },
        { time: "1:52", text: "shape right i'm just skipping over and", translation: "就係跳過一個音" },
        { time: "1:55", text: "taking every other note", translation: "攞隔一個音" },
        { time: "1:57", text: "and that is my doe chord", translation: "就係我嘅Do和弦" },
        { time: "1:59", text: "now i can go up to re into a ray chord", translation: "而家我可以上到Re，變成Re和弦" },
        { time: "2:02", text: "up to a me chord and so on", translation: "上到Mi和弦，如此類推" },
        { time: "2:04", text: "now the only thing is we don't want to", translation: "唯一係我哋唔想" },
        { time: "2:06", text: "call these chords do or re for the", translation: "叫呢啲和弦做Do或Re" },
        { time: "2:09", text: "chords we want to refer to them as", translation: "我哋想用" },
        { time: "2:11", text: "numbers like one two or three", translation: "數字，例如一、二、三" },
        { time: "2:14", text: "so there we go if we start on the first", translation: "所以如果我哋由第一個音開始" },
        { time: "2:16", text: "note of the scale we call it a one chord", translation: "我哋叫佢做一級和弦" },
        { time: "2:19", text: "if we start on the second note of the", translation: "如果我哋由第二個音開始" },
        { time: "2:20", text: "scale it's a two chord then three four", translation: "就係二級和弦，然後三、四" },
        { time: "2:23", text: "five and so on i think you get it pretty", translation: "五，如此類推，我覺得你明" },
        { time: "2:26", text: "simple right if you can count you can do", translation: "好簡單，如果你識數數" },
        { time: "2:28", text: "that", translation: "就可以做到" },
        { time: "2:29", text: "so now let's finally get to the ear", translation: "而家終於到聽力" },
        { time: "2:30", text: "training portion this is the reason", translation: "訓練部分，呢個就係" },
        { time: "2:32", text: "you're here and what we're gonna do is", translation: "你喺度嘅原因，我哋會做嘅係" },
        { time: "2:34", text: "i'm gonna play you a quick musical", translation: "我會播一段音樂" },
        { time: "2:36", text: "snippet and i'm not going to tell you", translation: "我唔會話你知" },
        { time: "2:38", text: "what you're listening for but i want you", translation: "你聽緊咩，但我想你" },
        { time: "2:39", text: "to listen closely and then we'll talk", translation: "仔細聽，然後我哋會講" },
        { time: "2:41", text: "about it afterwards i don't want to give", translation: "之後我唔想" },
        { time: "2:43", text: "anything away so check this out just", translation: "透露任何嘢，聽下呢個" },
        { time: "2:46", text: "take a listen", translation: "聽下" },
        { time: "2:54", text: "okay did something sound kind of off", translation: "好，有冇覺得有啲唔啱？" },
        { time: "2:55", text: "about that it did right", translation: "係有，對吧？" },
        { time: "3:00", text: "so what's happening is your ear knows", translation: "發生緊咩事？你隻耳知道" },
        { time: "3:03", text: "where it's supposed to go what your ear", translation: "應該去邊，你隻耳想聽" },
        { time: "3:05", text: "wants to hear is the sound of the one", translation: "到嘅係一級和弦" },
        { time: "3:07", text: "chord", translation: "嘅聲音" },
        { time: "3:08", text: "and the one chord the sound of it is", translation: "一級和弦嘅聲音係" },
        { time: "3:11", text: "resolution stability landing somewhere", translation: "解決、穩定、落腳點" },
        { time: "3:14", text: "okay so here's the one chord", translation: "好，呢個就係一級和弦" },
        { time: "3:19", text: "there we go so you knew the sound you", translation: "就係咁，你已經識呢個聲音" },
        { time: "3:22", text: "just didn't know what to call it now you", translation: "只係唔知叫咩名，而家你" },
        { time: "3:24", text: "know that that's the one chord so let me", translation: "知道就係一級和弦，等我" },
        { time: "3:26", text: "play another quick example", translation: "播另一個例子" },
        { time: "3:28", text: "here's the three chord", translation: "呢個係三級和弦" },
        { time: "3:30", text: "no goodness all right here's the one", translation: "唔啱，好，呢個係一級" },
        { time: "3:33", text: "chord", translation: "和弦" },
        { time: "3:36", text: "there we go now let's take the opposite", translation: "就係咁，而家我哋用相反" },
        { time: "3:38", text: "approach instead of me telling you", translation: "方法，唔係我話你知" },
        { time: "3:39", text: "here's what the one chord sounds like", translation: "一級和弦聽起上嚟係點" },
        { time: "3:41", text: "i'm gonna play a chord and i want you to", translation: "我會彈個和弦，我想你" },
        { time: "3:43", text: "tell me what it sounds like so think", translation: "話我知聽起上嚟係點，諗下" },
        { time: "3:46", text: "about if you had to put an emotion to", translation: "如果你要加個情緒" },
        { time: "3:47", text: "this what would that emotion be so i'll", translation: "會係咩情緒，我會" },
        { time: "3:50", text: "play a few chords just to get us in the", translation: "彈幾個和弦，等我哋入" },
        { time: "3:51", text: "key", translation: "調" },
        { time: "3:53", text: "now here's the chord in question", translation: "而家呢個係問題和弦" },
        { time: "3:57", text: "okay what's", translation: "好，係咩？" },
        { time: "3:58", text: "what's the sound of that is that happy", translation: "聽起上嚟係點？開心？" },
        { time: "4:01", text: "tense uh is it resolved like the one", translation: "緊張？定係解決咗，好似一級" },
        { time: "4:04", text: "chord", translation: "和弦？" },
        { time: "4:04", text: "i would probably say that's sad", translation: "我會話係傷心" },
        { time: "4:07", text: "right i mean it's not rocket science", translation: "對，我意思係唔係好難" },
        { time: "4:09", text: "like that's sort of a sad sound if i'm", translation: "就係有啲傷心嘅聲音，如果我" },
        { time: "4:11", text: "ending there", translation: "喺度結束" },
        { time: "4:14", text: "that is not a happy birthday uh which is", translation: "唔係開心生日歌，就係" },
        { time: "4:16", text: "kind of how i'm feeling now that i'm", translation: "我而家嘅感覺，因為我" },
        { time: "4:17", text: "getting up into my mid-30s but um yeah", translation: "就快三十幾歲，但係" },
        { time: "4:20", text: "so the six chord that's what i was", translation: "所以六級和弦，就係我" },
        { time: "4:22", text: "playing for you and the six chords sound", translation: "彈緊嘅，六級和弦嘅聲音" },
        { time: "4:25", text: "is fairly sad", translation: "係幾傷心" },
        { time: "4:27", text: "now there are other sad chords out there", translation: "而家都有其他傷心和弦" },
        { time: "4:29", text: "but you know the six chord is usually", translation: "但係六級和弦通常係" },
        { time: "4:31", text: "sort of our go-to for that sad sound", translation: "我哋用嚟做傷心聲音嘅" },
        { time: "4:33", text: "let's do one more example and this is", translation: "再做一個例子，呢個係" },
        { time: "4:35", text: "going to be the five chord so i want you", translation: "會係五級和弦，我想你" },
        { time: "4:37", text: "to listen to it and tell me what you", translation: "聽下，話我知你" },
        { time: "4:39", text: "think of this", translation: "覺得係點" },
        { time: "4:40", text: "right here", translation: "就係呢度" },
        { time: "4:43", text: "okay so that is really", translation: "好，呢個真係" },
        { time: "4:46", text: "dissonant and unresolved right i", translation: "不和諧同未解決，對，我" },
        { time: "4:48", text: "wouldn't end a song there", translation: "唔會喺度結束首歌" },
        { time: "4:49", text: "[Music]", translation: "[音樂]" },
        { time: "4:54", text: "right um so that is the polar opposite", translation: "對，所以呢個係完全相反" },
        { time: "4:56", text: "of the one chord it wants to pull", translation: "一級和弦，佢想拉" },
        { time: "4:59", text: "somewhere else uh sometimes i explain it", translation: "去其他地方，有時我解釋" },
        { time: "5:02", text: "as having motion because it wants to", translation: "係有動感，因為佢想" },
        { time: "5:03", text: "move but that is not a chord we'd end on", translation: "移動，但呢個唔係我哋會結束嘅和弦" },
        { time: "5:08", text: "you want to hear it go back to", translation: "你想聽佢返去" },
        { time: "5:10", text: "one so that's the five chord so there we", translation: "一級，所以呢個係五級和弦，就係咁" },
        { time: "5:13", text: "go we've already covered three of the", translation: "我哋已經講咗三個" },
        { time: "5:14", text: "seven chords within our language of", translation: "七個和弦，喺我哋音樂語言入面" },
        { time: "5:16", text: "music and if you can get all seven of", translation: "如果你識晒七個" },
        { time: "5:18", text: "them you're set and that's not to say", translation: "你就搞掂，唔係話" },
        { time: "5:21", text: "that you can't break the rules or bring", translation: "你唔可以打破規則或者" },
        { time: "5:23", text: "in other chords from outside that", translation: "用其他框架外嘅和弦" },
        { time: "5:24", text: "framework but i would estimate probably", translation: "但我估計大概" },
        { time: "5:26", text: "about 80 to 85 percent of everything", translation: "百分之八十到八十五嘅所有嘢" },
        { time: "5:29", text: "you're gonna hear is covered within what", translation: "你會聽到嘅都喺我哋講緊" },
        { time: "5:31", text: "we're talking about these seven chords", translation: "呢七個和弦入面" },
        { time: "5:33", text: "and of course we have to get the basics", translation: "當然我哋要掌握基礎" },
        { time: "5:35", text: "down before we can worry about breaking", translation: "先可以擔心打破" },
        { time: "5:37", text: "the rules before we worry about the", translation: "規則，先可以擔心" },
        { time: "5:39", text: "exceptions right we have to get the", translation: "例外，我哋要掌握" },
        { time: "5:41", text: "basics first", translation: "基礎先" },
        { time: "5:42", text: "so let's keep on going and let's talk", translation: "繼續，我哋講下" },
        { time: "5:44", text: "about melody a little bit for a lot of", translation: "旋律少少，對好多人嚟講" },
        { time: "5:46", text: "people melody is easier which is why i", translation: "旋律容易啲，所以我想" },
        { time: "5:48", text: "wanted to start with chords right i", translation: "由和弦開始，我想" },
        { time: "5:49", text: "wanted to get the scary stuff out of the", translation: "將難嘅嘢先做" },
        { time: "5:51", text: "way but for melody we can get a long way", translation: "但旋律我哋可以" },
        { time: "5:54", text: "towards playing by ear by doing interval", translation: "靠音程訓練，好大程度" },
        { time: "5:56", text: "training we can get ourselves a lot of", translation: "做到靠聽力彈，我哋可以" },
        { time: "5:58", text: "the way there", translation: "做到好多" },
        { time: "5:59", text: "and so interval training is singing what", translation: "音程訓練就係唱" },
        { time: "6:02", text: "we call intervals or the distances", translation: "我哋叫音程，或者距離" },
        { time: "6:05", text: "between different notes here's what i", translation: "唔同音之間，就係咁" },
        { time: "6:07", text: "mean if i sing dota ray", translation: "如果我唱Do到Re" },
        { time: "6:09", text: "that's two notes that's a second", translation: "就係兩個音，係二度" },
        { time: "6:12", text: "if i sing dota me", translation: "如果我唱Do到Mi" },
        { time: "6:14", text: "that's three notes so that's a third", translation: "就係三個音，係三度" },
        { time: "6:17", text: "okay so what we want to do is we want to", translation: "好，我哋想做嘅係" },
        { time: "6:19", text: "sing each of those intervals and that's", translation: "唱每個音程，呢個" },
        { time: "6:21", text: "going to help train our ear if you're in", translation: "會幫我哋訓練隻耳，如果你" },
        { time: "6:23", text: "a place where you can sing along with me", translation: "可以同我一齊唱" },
        { time: "6:24", text: "definitely do that and if you're not i", translation: "一定要做，如果你唔係" },
        { time: "6:27", text: "mean you could sing in public that'd be", translation: "你可以公開唱，會好" },
        { time: "6:28", text: "kind of awesome just do", translation: "正，就做" },
        { time: "6:30", text: "um but if you don't want to do that wait", translation: "但如果你唔想做，等" },
        { time: "6:32", text: "until you're in the car wait until", translation: "到喺車度，等到" },
        { time: "6:33", text: "you're at home and sing with me this is", translation: "你返到屋企同我一齊唱，呢個" },
        { time: "6:35", text: "not optional you've really got to sing", translation: "唔係選擇，你真係要唱" },
        { time: "6:37", text: "it to get it so here's our starting", translation: "先得，呢個係我哋嘅起始" },
        { time: "6:38", text: "pitch", translation: "音高" },
        { time: "6:39", text: "doh", translation: "Do" },
        { time: "6:40", text: "try and sing that", translation: "試下唱" },
        { time: "6:42", text: "do", translation: "Do" },
        { time: "6:43", text: "here we go", translation: "開始" },
        { time: "6:45", text: "[Music]", translation: "[音樂]" },
        { time: "7:23", text: "and it doesn't have to be perfect i'm", translation: "唔使完美，我" },
        { time: "7:24", text: "not warmed up today that was pretty", translation: "今日未熱身，有啲" },
        { time: "7:26", text: "pitchy but you know the point isn't to", translation: "走音，但重點唔係" },
        { time: "7:28", text: "be a great singer here it's just to", translation: "做個好歌手，只係" },
        { time: "7:30", text: "train your ear on how to get these", translation: "訓練你隻耳點樣得到" },
        { time: "7:32", text: "intervals now was that difficult for you", translation: "呢啲音程，對你難唔難？" },
        { time: "7:34", text: "or was it kind of easy i'm going to", translation: "定係幾易？我會" },
        { time: "7:36", text: "guess that it was kind of easy for you", translation: "估對你嚟講幾易" },
        { time: "7:38", text: "because again going back to the", translation: "因為再次返去" },
        { time: "7:40", text: "underlying theme of this whole video", translation: "成條片嘅主題" },
        { time: "7:42", text: "you've been exposed to scales your", translation: "你成世都接觸緊音階" },
        { time: "7:43", text: "entire life so going in and singing it", translation: "所以去唱佢" },
        { time: "7:46", text: "really isn't all that challenging and", translation: "真係唔係好難，同埋" },
        { time: "7:48", text: "the idea is you want to work with this", translation: "重點係你想做呢個" },
        { time: "7:50", text: "until you don't need the piano so the", translation: "直到你唔需要鋼琴，所以" },
        { time: "7:52", text: "next step is to sing it acapella and", translation: "下一步係無伴奏唱，然後" },
        { time: "7:54", text: "then check it with the piano", translation: "用鋼琴檢查" },
        { time: "7:56", text: "right so you're going to want to know", translation: "對，你會想識" },
        { time: "7:58", text: "your scales and there's tons of", translation: "你嘅音階，有好多" },
        { time: "7:59", text: "information out there on how to make", translation: "資料講點樣做" },
        { time: "8:00", text: "scales on whatever your instrument is so", translation: "任何樂器嘅音階，所以" },
        { time: "8:03", text: "i'm not going to cover that here", translation: "我唔會喺度講" },
        { time: "8:05", text: "but uh let's say we're doing the c scale", translation: "但假設我哋做C大調音階" },
        { time: "8:07", text: "i would sing", translation: "我會唱" },
        { time: "8:09", text: "do re let me check it", translation: "Do Re，等我檢查" },
        { time: "8:12", text: "yes re", translation: "係Re" },
        { time: "8:14", text: "then i might sing domi", translation: "然後我可能會唱Do Mi" },
        { time: "8:17", text: "that's right", translation: "啱" },
        { time: "8:21", text: "and i can check each one of those as i", translation: "我可以檢查每個，當我" },
        { time: "8:23", text: "go now of course that's just your", translation: "做緊，當然只係你" },
        { time: "8:25", text: "starting point for working with melody", translation: "做旋律嘅起點" },
        { time: "8:27", text: "there's a lot more to it because", translation: "有好多嘢，因為" },
        { time: "8:29", text: "melodies aren't going to always go back", translation: "旋律唔會成日返去" },
        { time: "8:30", text: "to dough they're going to flow from one", translation: "Do，佢哋會由一個" },
        { time: "8:32", text: "note to the next they're going to jump", translation: "音流去下一個，會跳" },
        { time: "8:34", text: "and skip and maybe start in places that", translation: "同跳過，可能會喺" },
        { time: "8:36", text: "aren't dough at all", translation: "完全唔係Do嘅地方開始" },
        { time: "8:37", text: "so there's a lot more to it but this is", translation: "所以有好多嘢，但呢個係" },
        { time: "8:39", text: "where you want to start same thing with", translation: "你想開始嘅地方，同" },
        { time: "8:41", text: "the chords there's more chords we can", translation: "和弦一樣，有更多和弦我哋可以" },
        { time: "8:43", text: "talk about but you've got to get your", translation: "講，但你要掌握你嘅" },
        { time: "8:44", text: "basics down first now if you're", translation: "基礎先，而家如果你" },
        { time: "8:46", text: "interested in going a little bit further", translation: "有興趣再深入少少" },
        { time: "8:48", text: "with me we ran out of time on this video", translation: "我哋呢條片時間用晒" },
        { time: "8:50", text: "i don't want it to be like you know", translation: "我唔想好似" },
        { time: "8:51", text: "three hour video", translation: "三小時片" },
        { time: "8:53", text: "but i do have a playing by ear course", translation: "但我有個靠聽力彈琴課程" },
        { time: "8:55", text: "that i sincerely think is the best thing", translation: "我真誠覺得係最好" },
        { time: "8:57", text: "out there on the internet if you want to", translation: "網上最好，如果你想" },
        { time: "8:59", text: "learn to play by ear and i even verified", translation: "學靠聽力彈，我甚至驗證過" },
        { time: "9:01", text: "that i bought some other people's", translation: "我買過其他人嘅" },
        { time: "9:02", text: "courses to see how they taught it and", translation: "課程睇佢哋點教，同埋" },
        { time: "9:05", text: "some of the courses didn't even have ear", translation: "有啲課程甚至冇聽力" },
        { time: "9:07", text: "training", translation: "訓練" },
        { time: "9:08", text: "you've got to actually use your ear and", translation: "你真係要用你隻耳，同埋" },
        { time: "9:10", text: "then you've got to connect it to your", translation: "然後你要連接到你嘅" },
        { time: "9:12", text: "instrument", translation: "樂器" },
        { time: "9:13", text: "so my training you know we obviously go", translation: "所以我嘅訓練，我哋明顯會" },
        { time: "9:14", text: "through all the chords we talk about", translation: "講晒所有和弦，我哋講" },
        { time: "9:16", text: "melodies there's rhythm exercises so you", translation: "旋律，有節奏練習，所以" },
        { time: "9:19", text: "know when to combine these elements", translation: "你知道幾時組合呢啲元素" },
        { time: "9:20", text: "together there's so much to it i can't", translation: "一齊，有好多嘢，我唔可以" },
        { time: "9:23", text: "even begin to describe all of it and if", translation: "開始描述所有嘢，如果你" },
        { time: "9:25", text: "you're interested in going a little bit", translation: "有興趣再深入少少" },
        { time: "9:26", text: "deeper i highly recommend you check out", translation: "我強烈建議你睇下" },
        { time: "9:28", text: "my piano by ear course", translation: "我嘅靠聽力彈琴課程" },
        { time: "9:30", text: "alright thank you so much for checking", translation: "好，多謝你睇" },
        { time: "9:32", text: "out this video i hope you loved it if", translation: "呢條片，我希望你鍾意，如果" },
        { time: "9:34", text: "you have any questions let me know and", translation: "你有任何問題話我知，同埋" },
        { time: "9:35", text: "i'll see you next time", translation: "下次見" }
    ],
    summary: {
        corePhilosophy: {
            title: "核心理念",
            text: "你的耳朵已經知道得比你以為的多得多。如果我們將音樂視為一種語言，那麼你一生都在接觸這種語言，你已經聽音樂聽了許多年。℗因此，基礎已經在那裡，無論你是否意識到，你只需要學會認出它們。℗這項技能絕對可以教，你不需要絕對音感或任何特殊天賦。"
        },
        songStructure: {
            title: "歌曲結構",
            text: "任何歌曲都可以分解為兩個基本元素：旋律和和弦。任何你想彈奏的歌曲都是旋律加上下方的和弦。因此，要訓練我們的耳朵，我們需要訓練這兩個領域。好消息是，它們都來自同一個來源：音階。"
        },
        scales: {
            title: "音階（Scale）：基礎",
            text: "音階是我們都熟悉的東西，就是經典的 Do-Re-Mi-Fa-So-La-Ti-Do。大多數人都知道旋律來自音階，只是這些音節的不同組合，例如 Do-Re-Mi 或 Re-Do-So-To。但許多人不知道的是，和弦也來自音階，不只是旋律。"
        },
        buildingChords: {
            title: "由音階建立和弦",
            text: "讓我們從 C 大調音階開始：Do-Re-Mi-Fa-So-La-Ti-Do。我們可以用「隔一個音」的模式將每個音變成和弦。如果我們從 Do 開始，跳過一個音，取隔一個音，就得到了 Do 和弦。同樣地，我們可以從 Re 得到 Re 和弦，從 Mi 得到 Mi 和弦，以此類推。℗我們不想用 Do 或 Re 來稱呼這些和弦，而是用數字系統：從音階的第一個音開始，我們稱之為一級和弦；從第二個音開始，是二級和弦；然後是三、四、五級，以此類推。℗這是一個非常簡單的概念：如果你會數數，你就懂了。"
        },
        chordRecognition: {
            title: "聽力訓練：和弦識別",
            text: "當你聽到一段音樂時，你的耳朵已經知道它應該去哪裡。你的耳朵想要聽到的是 I 和弦（一級和弦）的聲音，這個聲音代表著解決、穩定和落腳點。你已經熟悉這個聲音，只是不知道如何稱呼它。I 和弦讓歌曲聽起來「解決了」，像是可以結束的感覺。℗與之相反的是 V 和弦（五級和弦），它是不和諧、未解決的，與一級和弦完全相反。V 和弦製造張力，你會想聽它解決到一級，它不是會結束歌曲的和弦，而是製造「動感」，想拉去其他地方。℗vi 和弦（六級和弦）的聲音相當傷心、憂鬱和壓抑，不是開心的聲音，常見於情感或傷心歌曲。℗這七個和弦（I, ii, iii, IV, V, vi, vii°）涵蓋了百分之八十到八十五的所有音樂。本片詳細示範了 I、vi、V 三個和弦，幫助你開始識別這些基本的和弦聲音。重要的是先掌握這些基礎，之後再擔心例外。"
        },
        intervalTraining: {
            title: "旋律訓練：音程（Interval）訓練",
            text: "音程是音之間的距離。例如，Do 到 Re 是二度（兩個音），Do 到 Mi 是三度（三個音），以此類推。℗要訓練你的耳朵，你需要唱每個音程，這不是選項，而是必須的。由 Do 開始，唱到下一個音程，然後回到 Do。練習模式如 Do-Re-Do、Do-Mi-Do、Do-Fa-Do 等。℗關鍵步驟是無伴奏唱（沒有鋼琴），然後用鋼琴檢查。目標是做到不需要鋼琴參考也能唱出來。℗這之所以有效，是因為你一生都在接觸音階，唱音程並不難，因為你已經熟悉這些模式。℗下一階段是唱音階音，用鋼琴檢查。例如，唱「Do-Re」，然後檢查；唱「Do-Mi」，然後檢查。這只是起點，因為真正的旋律會流動、跳躍、跳過，不一定由 Do 開始，但這個基礎非常重要。"
        },
        keyTakeaways: {
            title: "核心重點",
            text: "聽力訓練是關鍵，你必須真正使用你的耳朵，而不只是學習理論。連接耳朵到樂器是連接「聽」與「彈」之間的橋樑。℗唱歌對有效訓練來說不是選項，而是必須的。℗從基礎開始，先掌握 I、IV、V、vi 和弦和音程訓練，之後再進入進階概念。℗重要的是要進行跨情境練習，既要獨立練習，也要應用到真實音樂中。"
        },
        practiceApproach: {
            title: "練習方法",
            text: "有效的練習方法包括訓練和弦識別（特別是 I、vi、V），透過唱歌訓練音程識別，練習唱音階並用鋼琴檢查，然後將這些技能應用到真實歌曲中。最終目標是建立聲音、感覺和理論之間的連接，這樣你就能真正理解音樂的內在結構。"
        }
    }
};
