const youtubeExample4Data = {
    videoId: "TOp-fsgnHIE",
    videoUrl: "https://www.youtube.com/watch?v=TOp-fsgnHIE",
    embedcode: "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/TOp-fsgnHIE?si=05u6B9OqkUQJACYs\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>",
    title: "Three-Step Process: Beginner to Advanced (Play by Ear)",
    cantoneseTitle: "三步過程：靠聽力彈新歌",
    transcript: [
        { time: "0:00", text: "I posted a video recently where I demonstrate learning a SZA song by ear", translation: "我最近post咗條片示範點樣靠聽力學SZA首歌" },
        { time: "0:04", text: "in about 30 seconds.", translation: "大約30秒" },
        { time: "0:05", text: "One commenter didn't believe it was possible, but it's absolutely possible.", translation: "有個留言者唔信可能，但絕對可能" },
        { time: "0:09", text: "And actually professional musicians just take it for granted", translation: "其實專業音樂人當呢個係理所當然" },
        { time: "0:12", text: "that everyone can do this.", translation: "人人都可以做" },
        { time: "0:13", text: "You don't need perfect pitch to be able to play by ear.", translation: "你唔需要絕對音感先可以靠聽力彈" },
        { time: "0:16", text: "In fact, I do not have perfect pitch, even after all these years of playing piano.", translation: "其實我冇絕對音感，就算彈咗咁多年鋼琴" },
        { time: "0:21", text: "I cannot reliably sing Middle C without a reference pitch.", translation: "我冇參考音就唱唔到Middle C" },
        { time: "0:26", text: "Uh, totally wrong.", translation: "完全錯" },
        { time: "0:29", text: "But I can learn songs by ear in one or two lessons.", translation: "但我可以一兩堂就靠聽力學到首歌" },
        { time: "0:33", text: "To do that,", translation: "要做到呢個" },
        { time: "0:33", text: "I use the same three step process I've been using since I was a teenager.", translation: "我用同一個三步過程，由十幾歲用到而家" },
        { time: "0:37", text: "I've gotten a lot better at the process over time,", translation: "我對呢個過程熟練咗好多" },
        { time: "0:40", text: "but the three steps have remained the same.", translation: "但三步保持一樣" },
        { time: "0:42", text: "So I want to show you", translation: "所以我想示範俾你睇" },
        { time: "0:43", text: "those three steps will apply them to a few example songs and look at", translation: "呢三步，應用喺幾個例子歌，睇下" },
        { time: "0:47", text: "how as your ears improves over time, that process will gradually change.", translation: "你隻耳進步時，過程會點樣逐漸改變" },
        { time: "0:51", text: "For a first example song, Let's use Cruel Summer by Taylor Swift.", translation: "第一個例子歌，我哋用Taylor Swift嘅Cruel Summer" },
        { time: "0:54", text: "Sound like this.", translation: "聽起上嚟係咁" },
        { time: "1:07", text: "So our three steps are simple.", translation: "所以我哋三步好簡單" },
        { time: "1:09", text: "Find the key.", translation: "搵調" },
        { time: "1:10", text: "Find the bassline, Find the chords.", translation: "搵低音線，搵和弦" },
        { time: "1:12", text: "Let's look at how this plays out.", translation: "我哋睇下點樣進行" },
        { time: "1:13", text: "If you're new to playing by ear", translation: "如果你係靠聽力彈嘅新手" },
        { time: "1:15", text: "to find the key, you can basically just use trial and error.", translation: "搵調，基本上可以用試錯法" },
        { time: "1:18", text: "Now you will need to know your major scales.", translation: "而家你需要識大調音階" },
        { time: "1:21", text: "So if you already aren't familiar with your major scales,", translation: "所以如果你未熟大調音階" },
        { time: "1:23", text: "you can grab my visual guide to all the major scales.", translation: "你可以攞我嘅大調音階視覺指南" },
        { time: "1:26", text: "And I do have some other videos on how to practice your scales.", translation: "我都有其他片講點樣練習音階" },
        { time: "1:29", text: "So in the early stages you're going to rely heavily on trial and error.", translation: "所以早期階段你會大量依賴試錯" },
        { time: "1:32", text: "And if you're coming from playing classical music or tutorials,", translation: "如果你係彈古典音樂或教程過嚟" },
        { time: "1:37", text: "the first thing to get used to is the idea that you're", translation: "第一樣要習慣嘅係你" },
        { time: "1:39", text: "not going to break the instrument.", translation: "唔會整壞樂器" },
        { time: "1:41", text: "If you play wrong notes.", translation: "如果你彈錯音" },
        { time: "1:43", text: "I encourage you to just kind of make a mess.", translation: "我鼓勵你亂彈" },
        { time: "1:46", text: "Don't worry about playing something wrong and you can play along with the recording", translation: "唔好擔心彈錯，你可以同錄音一齊彈" },
        { time: "1:51", text: "and just start to listen for notes that sound like they fit.", translation: "開始聽邊啲音聽起上嚟啱" },
        { time: "1:54", text: "Pretty soon you'll start to gather a little collection of notes", translation: "好快你會收集到一啲音" },
        { time: "1:57", text: "that all feel like they really belong with this song.", translation: "都感覺屬於首歌" },
        { time: "2:00", text: "And even people with really untrained ears tend to be pretty good at this.", translation: "就算未訓練過嘅耳都做得幾好" },
        { time: "2:04", text: "If you're hearing a chord progression that goes like this,", translation: "如果你聽到和弦進行係咁" },
        { time: "2:06", text: "this note is going to sound really out of place.", translation: "呢個音會聽起上嚟好唔啱" },
        { time: "2:09", text: "Let's say I'm pretty confident that all four of these notes sound good", translation: "假設我好肯定呢四個音都啱" },
        { time: "2:13", text: "with Cruel Summer.", translation: "同Cruel Summer" },
        { time: "2:14", text: "A, B, C, Sharp, and E.", translation: "A, B, C#, 同E" },
        { time: "2:18", text: "That's only four notes, but", translation: "只係四個音，但" },
        { time: "2:20", text: "I've already ruled out most of the possible major keys.", translation: "我已經排除咗大部分可能嘅大調" },
        { time: "2:23", text: "There are only three keys that include all four of those notes.", translation: "只有三個調包含呢四個音" },
        { time: "2:26", text: "A major", translation: "A大調" },
        { time: "2:29", text: "D major", translation: "D大調" },
        { time: "2:32", text: "and E major.", translation: "同E大調" },
        { time: "2:35", text: "So now that I have some guesses", translation: "所以而家我有啲猜測" },
        { time: "2:37", text: "about what key this might be in, I can try playing those major scales", translation: "首歌可能係咩調，我可以試彈呢啲大調音階" },
        { time: "2:41", text: "along with the recording, or immediately after listening to part of the recording.", translation: "同錄音一齊，或者聽完錄音部分之後立即" },
        { time: "2:45", text: "And one might stick out to me as really feeling like it belongs with the song.", translation: "一個可能會突出，感覺屬於首歌" },
        { time: "2:50", text: "You're listening for a sense of resolution that when you play the scale", translation: "你聽緊解決感，當你彈音階" },
        { time: "2:53", text: "and you arrive at the top of the scale,", translation: "去到音階頂" },
        { time: "2:57", text: "that also sounds like that", translation: "聽起上嚟都好似" },
        { time: "2:58", text: "could be the ending of this song,", translation: "可以係首歌結尾" },
        { time: "3:02", text: "often a really great give away for the sound of the key of the song", translation: "通常係首歌調性聲音嘅好提示" },
        { time: "3:06", text: "is the end of a phrase or the end of the song,", translation: "係樂句結尾或歌曲結尾" },
        { time: "3:08", text: "because that's where things are likely to sound resolved.", translation: "因為呢度通常聽起上嚟解決咗" },
        { time: "3:11", text: "And a lot of times songwriters end things on the one chord.", translation: "好多時作曲人會用一級和弦結束" },
        { time: "3:15", text: "Let's say I've arrived at a as the key that I think we're in for Cruel Summer.", translation: "假設我搵到A係我認為Cruel Summer嘅調" },
        { time: "3:23", text: "That makes the rest of my job much easier", translation: "呢個令我其他工作容易好多" },
        { time: "3:26", text: "because here, as we go to step to finding the bass line, we can always just start", translation: "因為去到搵低音線步驟，我哋可以開始" },
        { time: "3:31", text: "with the notes that belong in the key, as are reasonable guesses.", translation: "用屬於調嘅音，係合理猜測" },
        { time: "3:35", text: "There are times in pop music where the bass line will go", translation: "流行音樂有時低音線會" },
        { time: "3:39", text: "outside the key, but they're relatively uncommon.", translation: "離開調，但相對少見" },
        { time: "3:42", text: "So we've narrowed our guesses down from 12 possible pitches", translation: "所以我哋將猜測由12個可能音高" },
        { time: "3:46", text: "for each of those bass notes to just seven that belong in the scale.", translation: "收窄到每個低音只有7個屬於音階嘅音" },
        { time: "3:49", text: "And now we listen for the baseline.", translation: "而家我哋聽低音線" },
        { time: "3:51", text: "We're listening for where it sounds like the chords are changing.", translation: "我哋聽緊邊度聽起上嚟和弦轉換" },
        { time: "3:54", text: "And right at the beginning of that new chord change,", translation: "新和弦變化開始時" },
        { time: "3:57", text: "listen for the lowest note that you can hear.", translation: "聽最低可以聽到嘅音" },
        { time: "3:59", text: "Two things can really help with this.", translation: "兩樣嘢可以幫到" },
        { time: "4:01", text: "Use the best headphones or speakers that you have", translation: "用你最好嘅耳機或喇叭" },
        { time: "4:04", text: "because if you're using just like a phone speaker,", translation: "因為如果你用電話喇叭" },
        { time: "4:07", text: "it will actually cut out a lot of those lower frequencies.", translation: "會cut好多低頻" },
        { time: "4:10", text: "So it doesn't matter how good your ear is if you're trying to listen on", translation: "所以就算你隻耳幾好，如果用" },
        { time: "4:13", text: "an iPhone speaker, you might not be able to hear the bass notes of the recording.", translation: "iPhone喇叭，你可能聽唔到錄音嘅低音" },
        { time: "4:17", text: "Another tip is to play these bass notes.", translation: "另一個提示係彈呢啲低音" },
        { time: "4:20", text: "When you're testing your guesses", translation: "當你測試猜測時" },
        { time: "4:22", text: "in a bass register, play them low on your instrument.", translation: "低音域，喺樂器上彈低啲" },
        { time: "4:26", text: "Sometimes melody notes are different than bass notes,", translation: "有時旋律音同低音唔同" },
        { time: "4:30", text: "and they can even rub against bass notes.", translation: "甚至會同低音摩擦" },
        { time: "4:32", text: "If you play the bass notes too high on your instrument.", translation: "如果你喺樂器上彈低音太高" },
        { time: "4:35", text: "For example, the last bass note in this Taylor Swift example", translation: "例如，呢個Taylor Swift例子最後低音" },
        { time: "4:43", text: "is a D, and we have C-sharp in the melody.", translation: "係D，旋律有C#" },
        { time: "4:47", text: "Exactly when that bass note lands.", translation: "就係低音落嗰時" },
        { time: "4:49", text: "So if you're testing the bass note up here, you might even be correct", translation: "所以如果你喺上面測試低音，你可能啱" },
        { time: "4:52", text: "about the bass note.", translation: "低音係啱" },
        { time: "4:53", text: "You think it might be a D, but because the melody is on a C-sharp,", translation: "你以為係D，但因為旋律係C#" },
        { time: "4:58", text: "it sounds wrong.", translation: "聽起上嚟錯" },
        { time: "4:59", text: "So make sure you're testing out these bass notes in a low register.", translation: "所以確保你喺低音域測試呢啲低音" },
        { time: "5:02", text: "Listen through.", translation: "聽晒" },
        { time: "5:03", text: "Listen for the lowest note you can hear as you move from one chord to the next.", translation: "聽最低可以聽到嘅音，當你由一個和弦去下一個" },
        { time: "5:07", text: "And especially if you're new to this, I suggest you go ahead and write these down", translation: "特別係如果你係新手，我建議你寫低" },
        { time: "5:10", text: "as you find a bass note and you feel confident about it, write it down.", translation: "當你搵到低音同有信心，寫低佢" },
        { time: "5:15", text: "In Cruel Summer, we have a", translation: "Cruel Summer入面，我哋有" },
        { time: "5:19", text: "C-sharp,", translation: "C#" },
        { time: "5:22", text: "the F Sharp", translation: "F#" },
        { time: "5:24", text: "and D,", translation: "同D" },
        { time: "5:30", text: "and those are the four bass notes we hear in the chorus chord progression.", translation: "就係我哋喺副歌和弦進行聽到嘅四個低音" },
        { time: "5:33", text: "Once we've written down those bass notes and we know the key of the song again,", translation: "寫低低音同知道首歌調之後" },
        { time: "5:37", text: "we've made our job a lot easier by narrowing the possibilities", translation: "我哋收窄可能性，工作容易好多" },
        { time: "5:41", text: "for each of those bass notes.", translation: "對每個低音" },
        { time: "5:42", text: "There are only a couple likely chords that will go with the note.", translation: "只有幾個可能和弦配合個音" },
        { time: "5:47", text: "So for A,", translation: "所以對A" },
        { time: "5:48", text: "if we're in the key of a major, it's probably going to be in a major chord.", translation: "如果我哋係A大調，可能係大和弦" },
        { time: "5:52", text: "And at this point, you can just test your guess", translation: "而家你可以測試你嘅猜測" },
        { time: "5:56", text: "and play it along with the", translation: "同首歌一齊彈" },
        { time: "5:57", text: "song and see if it sounds right for all the rest of these bass notes.", translation: "睇下對其他低音係咪都啱" },
        { time: "6:00", text: "You should start with your guess being the diatonic chord.", translation: "你應該由自然音階和弦開始猜測" },
        { time: "6:03", text: "That is the chord that only uses notes that belong in the scale.", translation: "就係只用屬於音階音嘅和弦" },
        { time: "6:08", text: "So for C-sharp, that's the third note of the scale.", translation: "所以對C#，係音階第三個音" },
        { time: "6:11", text: "We should try a minor chord first", translation: "我哋應該先試小和弦" },
        { time: "6:14", text: "for F sharp.", translation: "對F#" },
        { time: "6:15", text: "That's the six.", translation: "係六級" },
        { time: "6:16", text: "That's also usually going to be minor,", translation: "通常都係小" },
        { time: "6:19", text: "and for D, that's four.", translation: "對D，係四級" },
        { time: "6:21", text: "And that's usually a major chord.", translation: "通常係大和弦" },
        { time: "6:25", text: "In the case of this example song, those chords are all correct.", translation: "呢個例子歌，呢啲和弦都啱" },
        { time: "6:28", text: "So your first guess, even without having heard the song, if you just looked at all", translation: "所以你第一個猜測，就算未聽過首歌，如果只係睇" },
        { time: "6:34", text: "those bass notes, your first guess based on the key of the song, would be correct.", translation: "呢啲低音，基於首歌調嘅第一個猜測會啱" },
        { time: "6:38", text: "That's the power of knowing the key of a song.", translation: "就係知道首歌調嘅力量" },
        { time: "6:40", text: "So at this point, we know the chord progression to Cruel Summer.", translation: "所以而家我哋知道Cruel Summer嘅和弦進行" },
        { time: "6:43", text: "It's a", translation: "係" },
        { time: "6:44", text: "C-sharp minor, F, sharp minor, and D,", translation: "C#小、F#小、同D" },
        { time: "6:49", text: "And if you want to go on and as a bonus,", translation: "如果你想繼續，作為獎勵" },
        { time: "6:51", text: "find the melody on the piano, you can do that too.", translation: "搵鋼琴上嘅旋律，你都可以做" },
        { time: "6:54", text: "Basically using the same process we used for finding the bass notes,", translation: "基本上用同搵低音一樣嘅過程" },
        { time: "6:58", text: "you know, you're limiting your guesses to notes", translation: "你限制猜測到音" },
        { time: "6:59", text: "that do belong in the scale as a great starting point.", translation: "屬於音階嘅，係好起點" },
        { time: "7:03", text: "And just don't be afraid to use trial and error.", translation: "唔好怕用試錯法" },
        { time: "7:05", text: "Okay, so the first few dozen times you try doing this,", translation: "好，頭幾十次你做呢個" },
        { time: "7:09", text: "you might need to rely really heavily on trial and error.", translation: "你可能要大量依賴試錯" },
        { time: "7:12", text: "The next stage of development is starting to rely more on your ear apart", translation: "下個發展階段係開始更多依賴你隻耳" },
        { time: "7:17", text: "from the instrument, and be able to hear what's going on before you test things.", translation: "離開樂器，測試前先聽到發生緊咩" },
        { time: "7:22", text: "Let's use a new example song for this.", translation: "我哋用新例子歌" },
        { time: "7:24", text: "Let's use Vampire by Olivia Rodrigo.", translation: "我哋用Olivia Rodrigo嘅Vampire" },
        { time: "7:26", text: "That sounds like this.", translation: "聽起上嚟係咁" },
        { time: "7:43", text: "Now we're going to", translation: "而家我哋會" },
        { time: "7:43", text: "try and find the sound of one,", translation: "試搵「一」嘅聲音" },
        { time: "7:46", text: "the sound of the key of the song before we even test anything on the piano.", translation: "首歌調嘅聲音，測試鋼琴前" },
        { time: "7:51", text: "So I'm going to try and sing a note that sounds like it's resolved.", translation: "所以我會試唱一個聽起上嚟解決咗嘅音" },
        { time: "7:54", text: "It sounds like it could be the end of the song, but", translation: "聽起上嚟可以係首歌結尾，但" },
        { time: "7:59", text: "that note sounds like it could be the end of the song.", translation: "呢個音聽起上嚟可以係首歌結尾" },
        { time: "8:02", text: "Another note could maybe be, but that note also sounds pretty stable.", translation: "另一個音可能係，但呢個音都聽起上嚟幾穩定" },
        { time: "8:07", text: "And in fact, most people will do a pretty good job", translation: "其實大部分人會做得幾好" },
        { time: "8:11", text: "of generally singing either one or five, the first or fifth notes of a major scale.", translation: "通常唱一或五，大調音階第一或第五個音" },
        { time: "8:17", text: "When they're looking for a note that sounds like it's resolved", translation: "當佢哋搵聽起上嚟解決咗嘅音時" },
        { time: "8:20", text: "sometimes people will be led astray by a melody note", translation: "有時人會被旋律音誤導" },
        { time: "8:23", text: "that's different than the one or the five.", translation: "同一個或五唔同" },
        { time: "8:25", text: "Our ear tends to just gravitate towards what we're hearing in the melody.", translation: "我哋隻耳傾向被旋律聽到嘅嘢吸引" },
        { time: "8:29", text: "But if you can", translation: "但如果你可以" },
        { time: "8:29", text: "listen for the end of a phrase or the end of the song, a lot of times", translation: "聽樂句結尾或歌曲結尾，好多時" },
        { time: "8:33", text: "you'll be able to hear what sounds like the most resolved note.", translation: "你會聽到最解決嘅音" },
        { time: "8:37", text: "So just practice trying to sing one.", translation: "所以練習試唱一" },
        { time: "8:39", text: "And this might seem really hard at first, but you're actually probably better", translation: "呢個可能最初好難，但你其實可能好過" },
        { time: "8:43", text: "than you think at recognizing the sound of", translation: "你以為喺識別聲音" },
        { time: "8:46", text: "what is resolved in a piece of music.", translation: "音樂中解決咗嘅嘢" },
        { time: "8:49", text: "If you hear a piece like this", translation: "如果你聽到一段音樂係咁" },
        { time: "8:54", text: "and then", translation: "然後" },
        { time: "8:56", text: "you hear a", translation: "你聽到" },
        { time: "8:57", text: "note or a chord that doesn't belong in the key,", translation: "音或和弦唔屬於調" },
        { time: "9:00", text: "you'll probably recognize that It sounds weird or it sounds wrong.", translation: "你可能會認出聽起上嚟奇怪或錯" },
        { time: "9:04", text: "And the flipside of that is that you're probably pretty good at recognizing", translation: "相反係你可能幾好識認出" },
        { time: "9:07", text: "when something sounds like it does belong, or it's the natural ending to the piece.", translation: "嘢聽起上嚟屬於，或係作品自然結尾" },
        { time: "9:12", text: "So you have likely been hearing the sound of one your whole life.", translation: "所以你成世都可能聽緊「一」嘅聲音" },
        { time: "9:18", text: "We're just trying to put a name to it", translation: "我哋只係試緊俾個名佢" },
        { time: "9:20", text: "and get you to be able to sing it after hearing a piece of music.", translation: "令你聽完音樂後可以唱到" },
        { time: "9:23", text: "Now, when you're first doing this,", translation: "而家，當你第一次做呢個" },
        { time: "9:24", text: "you might not be confident at all that you're singing one correctly,", translation: "你可能完全冇信心你唱一係啱" },
        { time: "9:28", text: "but you can test for yourself whether you're right.", translation: "但你可以自己測試係咪啱" },
        { time: "9:30", text: "And again, this is where we'll use our knowledge of scales on the piano.", translation: "再次，呢度我哋用鋼琴上音階知識" },
        { time: "9:33", text: "If I think PA is one for vampire,", translation: "如果我覺得PA係vampire嘅一" },
        { time: "9:39", text: "then I'm going to try finding that note on piano.", translation: "然後我會試搵鋼琴上嗰個音" },
        { time: "9:42", text: "But I'll just sing until I can match that pitch with the piano.", translation: "但我會唱直到可以同鋼琴音高匹配" },
        { time: "9:48", text: "And then now I think it might be an F.", translation: "然後而家我覺得可能係F" },
        { time: "9:51", text: "I'm going to play the F major scale,", translation: "我會彈F大調音階" },
        { time: "9:54", text: "and just as we did in the easy version, will", translation: "就同簡單版本一樣，會" },
        { time: "9:58", text: "listen for whether that scale sounds like it belongs with the piece.", translation: "聽下音階係咪聽起上嚟屬於作品" },
        { time: "10:01", text: "The most common mistake is mistaking five for one,", translation: "最常見錯誤係將五誤認為一" },
        { time: "10:05", text: "and there will be one note that's wrong if you choose that scale.", translation: "如果你選呢個音階，會有一個音錯" },
        { time: "10:08", text: "So in this case, five would be bar a C", translation: "所以呢個情況，五會係C" },
        { time: "10:11", text: "in the key of F and", translation: "F調入面" },
        { time: "10:15", text: "this note", translation: "呢個音" },
        { time: "10:18", text: "does not belong with the piece, so that'll be your giveaway.", translation: "唔屬於作品，所以會係你嘅提示" },
        { time: "10:21", text: "If you choose five instead of one for what you think is the root note of the song.", translation: "如果你選五而唔係一作為你認為首歌嘅根音" },
        { time: "10:26", text: "One other tip that has helped some of my students with", translation: "另一個幫到我學生嘅提示" },
        { time: "10:28", text: "this is you can try singing one and then singing a few notes in this scale", translation: "係你可以試唱一，然後唱音階幾個音" },
        { time: "10:32", text: "in either direction, but I think that's one.", translation: "兩個方向，但我覺得係一" },
        { time: "10:35", text: "Can I sing to 321767151.", translation: "我可以唱到321767151" },
        { time: "10:42", text: "If you can sort of sing your way around a major scale", translation: "如果你可以唱大調音階周圍" },
        { time: "10:45", text: "on either side of what you think is the right note, you can listen", translation: "你認為啱音兩邊，你可以聽" },
        { time: "10:50", text: "for whether that feels like it makes sense with the sound of the song.", translation: "係咪感覺同首歌聲音有道理" },
        { time: "10:53", text: "So that's step one at an intermediate level.", translation: "所以係中級水平第一步" },
        { time: "10:56", text: "Listen to the song", translation: "聽首歌" },
        { time: "10:57", text: "and see if you can sing The Root and then find that note on the piano.", translation: "睇下你可唔可以唱根音，然後搵鋼琴上嗰個音" },
        { time: "11:01", text: "And that's how you'll find the key of the song.", translation: "就係咁你搵到首歌調" },
        { time: "11:03", text: "For step two.", translation: "第二步" },
        { time: "11:04", text: "At an intermediate level, we're finding the bass notes, but", translation: "中級水平，我哋搵低音，但" },
        { time: "11:06", text: "we're going to try and do it more by ear, and we'll do that with scale degrees.", translation: "我哋會試更多用耳，用音階度數做" },
        { time: "11:10", text: "So this is called functional ear training.", translation: "所以呢個叫功能聽力訓練" },
        { time: "11:12", text: "We get situated in a certain key and then we're identifying notes with numbers.", translation: "我哋喺某個調定位，然後用數字識別音" },
        { time: "11:18", text: "There's an app,", translation: "有個app" },
        { time: "11:19", text: "a free app that I highly recommend for this is called Functional Ears Trainer,", translation: "免費app我強烈推薦叫Functional Ears Trainer" },
        { time: "11:22", text: "and you can also practice this skill by practicing taking simple melodies", translation: "你都可以練習簡單旋律" },
        { time: "11:26", text: "and putting them in lots of different keys.", translation: "放喺好多唔同調" },
        { time: "11:28", text: "Sight singing is another great way to practice this skill.", translation: "視唱係另一個好方法練習呢個技能" },
        { time: "11:32", text: "This is basically the skill of self edge movable dough, self edge", translation: "基本上係可移動do嘅技能" },
        { time: "11:36", text: "learning to recognize notes within a key by their numbers.", translation: "學用數字識別調內音" },
        { time: "11:40", text: "So that's the intermediate level of listening for baselines.", translation: "所以係中級水平聽低音線" },
        { time: "11:43", text: "Without testing on the instrument, you're going to try and listen", translation: "唔測試樂器，你會試聽" },
        { time: "11:45", text: "for that bass note again, use headphones or great speakers", translation: "低音，用耳機或好喇叭" },
        { time: "11:49", text: "and you're just going to be hearing numbers.", translation: "你只會聽到數字" },
        { time: "11:51", text: "So in the case of this Olivia Rodrigo song, I would hear one,", translation: "所以呢首Olivia Rodrigo歌，我會聽到一" },
        { time: "11:57", text: "three,", translation: "三" },
        { time: "12:00", text: "four, and then another kind of four.", translation: "四，然後另一個四" },
        { time: "12:06", text: "And that's how I would find that bass line.", translation: "就係咁我搵到低音線" },
        { time: "12:08", text: "In the key of F, those numbers will be F,", translation: "F調入面，呢啲數字會係F" },
        { time: "12:11", text: "A and B flat twice and again for step three.", translation: "A同B♭兩次，然後第三步" },
        { time: "12:16", text: "At an intermediate level,", translation: "中級水平" },
        { time: "12:17", text: "you can start to push yourself to identify the kind of chord", translation: "你可以推自己識別和弦種類" },
        { time: "12:21", text: "associated with each of these bass notes before you test on the instrument.", translation: "同每個低音相關，測試樂器前" },
        { time: "12:26", text: "You can rely on your theory knowledge to narrow your guesses down.", translation: "你可以靠理論知識收窄猜測" },
        { time: "12:30", text: "Probably the one chord is major", translation: "可能一和弦係大" },
        { time: "12:35", text: "probable.", translation: "可能" },
        { time: "12:35", text: "The three chord is minor,", translation: "三和弦係小" },
        { time: "12:39", text: "probably the four chord as major.", translation: "可能四和弦係大" },
        { time: "12:43", text: "In the case of this song,", translation: "呢首歌情況" },
        { time: "12:44", text: "two of those chords actually are non diatonic.", translation: "兩個和弦其實係非自然音階" },
        { time: "12:48", text: "That means they use a chord quality other than the one in the song.", translation: "即係用咗同首歌唔同嘅和弦性質" },
        { time: "12:52", text: "But look, when the three is in the bass,", translation: "但睇，當三係低音時" },
        { time: "12:55", text: "it's usually either minor or major, and it's actually fairly common", translation: "通常係小或大，其實幾常見" },
        { time: "12:59", text: "in pop songs for the three to be used as a major chord or a dominant chord.", translation: "流行歌三會用做大和弦或屬和弦" },
        { time: "13:04", text: "So over time you'll start to recognize the difference between the sound", translation: "所以隨時間你會開始識別聲音差異" },
        { time: "13:06", text: "of a three minor chord and a three major chord, and in this case,", translation: "三小和弦同三大和弦，呢個情況" },
        { time: "13:13", text: "when I hear that three in the bass, I can recognize that it has", translation: "當我聽到三係低音，我可以認出有" },
        { time: "13:16", text: "that sort of strong pull upward", translation: "強烈向上拉" },
        { time: "13:19", text: "that a three chord played as a major chord has.", translation: "三和弦做大和弦有嘅" },
        { time: "13:22", text: "You'll have to do trial and error to get good at this,", translation: "你要做試錯先做得好" },
        { time: "13:24", text: "but over time you'll start to recognize the way that these different chord", translation: "但隨時間你會開始識別呢啲唔同和弦" },
        { time: "13:27", text: "functions sound when they're either major or minor.", translation: "功能聽起上嚟係大或小" },
        { time: "13:31", text: "And there just aren't that many different options for possible", translation: "冇咁多唔同選項可能" },
        { time: "13:34", text: "chords over any of these possible bass notes.", translation: "和弦對任何可能低音" },
        { time: "13:37", text: "Usually the first options are either major or minor, and you should start", translation: "通常第一個選項係大或小，你應該開始" },
        { time: "13:41", text: "with the ones that make sense in the key of the song.", translation: "用首歌調入面有道理嘅" },
        { time: "13:44", text: "And then maybe you can branch out from there to other chord qualities", translation: "然後可能你可以擴展到其他和弦性質" },
        { time: "13:48", text: "like inversions of chords or seventh chords and so on.", translation: "例如和弦轉位或七和弦等" },
        { time: "13:53", text: "But usually in pop music you really only have to look at those", translation: "但通常流行音樂你只係要睇" },
        { time: "13:56", text: "first couple most likely guesses for the chord", translation: "頭幾個最可能猜測對和弦" },
        { time: "13:59", text: "functions to figure out what kind of court it is once you know the bass note.", translation: "功能去搵係咩種類，一旦你知道低音" },
        { time: "14:03", text: "So with this Olivia Rodrigo's song,", translation: "所以呢首Olivia Rodrigo歌" },
        { time: "14:05", text: "we know that the bass notes are one, three, four and another four.", translation: "我哋知道低音係一、三、四同另一個四" },
        { time: "14:09", text: "And my ear is very familiar with the sound of one is a major chord.", translation: "我隻耳好熟一係大和弦嘅聲音" },
        { time: "14:14", text: "Three as a major chord,", translation: "三做大和弦" },
        { time: "14:17", text: "four is a major chord, and then four becoming a minor chord.", translation: "四係大和弦，然後四變成小和弦" },
        { time: "14:21", text: "So as you're getting better and better", translation: "所以當你越嚟越好" },
        { time: "14:23", text: "at doing this, I suggest you push yourself to make a guess", translation: "做呢個，我建議你推自己猜測" },
        { time: "14:26", text: "for each of these chord functions before you test them on the piano.", translation: "對每個和弦功能，測試鋼琴前" },
        { time: "14:30", text: "You might have already found out", translation: "你可能已經搵到" },
        { time: "14:31", text: "that the song is in the key of F, but try and write down. Okay.", translation: "首歌係F調，但試寫低。好" },
        { time: "14:34", text: "Do I think this is a three major chord or a three", translation: "我覺得係三大和弦定三" },
        { time: "14:38", text: "minor chord and write down your guesses", translation: "小和弦，寫低你嘅猜測" },
        { time: "14:41", text: "and then you can test and get feedback by trying these things on the piano", translation: "然後你可以測試同得到反饋，試呢啲嘢喺鋼琴" },
        { time: "14:45", text: "and seeing whether they sound right.", translation: "睇下係咪聽起上嚟啱" },
        { time: "14:46", text: "Now, speaking from personal experience here, I did this for a long time before", translation: "而家，講個人經驗，我做咗好耐先" },
        { time: "14:51", text: "I started to get to the place where I could hear chord progressions as numbers", translation: "開始去到可以聽到和弦進行作為數字" },
        { time: "14:56", text: "and feel really confident about my guesses without testing at the instrument.", translation: "對猜測好有信心，唔測試樂器" },
        { time: "15:01", text: "But that will start to happen if you keep practicing this for a number of years.", translation: "但如果你持續練習幾年會開始發生" },
        { time: "15:06", text: "And when that started to happen, there was this kind of amazing thing", translation: "當開始發生時，有呢種神奇嘢" },
        { time: "15:10", text: "that happened in my life where suddenly as I was going about my day", translation: "發生喺我生活，突然當我過日子時" },
        { time: "15:14", text: "just hearing music, I knew what I was hearing.", translation: "只係聽到音樂，我知道聽緊咩" },
        { time: "15:18", text: "The interesting thing is that if you have relative pitch, you'll be hearing", translation: "有趣係如果你有相對音感，你會聽到" },
        { time: "15:21", text: "everything as numbers and the numbers might be accurate.", translation: "所有嘢作為數字，數字可能準確" },
        { time: "15:25", text: "But if I'm visualizing those numbers being played on a piano keyboard,", translation: "但如果我將數字可視化喺鋼琴鍵盤上" },
        { time: "15:29", text: "I'm not actually confident about what key it's in.", translation: "我其實唔肯定係咩調" },
        { time: "15:32", text: "So a lot of times I might be visualizing playing a song", translation: "所以好多時我可能可視化彈歌" },
        { time: "15:36", text: "in the wrong key with all of the numbers.", translation: "錯調，所有數字" },
        { time: "15:38", text: "Correct.", translation: "啱" },
        { time: "15:39", text: "So like going back to that Taylor Swift song,", translation: "所以好似返去Taylor Swift首歌" },
        { time: "15:41", text: "if I were to hear that song and not have a piano nearby,", translation: "如果我聽到首歌但附近冇鋼琴" },
        { time: "15:44", text: "I might think, Well, maybe the song's in C and I'll be hearing everything as", translation: "我可能諗，可能首歌係C調，我會聽到所有嘢作為" },
        { time: "15:57", text: "So you can hear it.", translation: "所以你可以聽到" },
        { time: "16:00", text: "That's the song.", translation: "就係首歌" },
        { time: "16:01", text: "It sounds correct, but it's it's in the wrong key.", translation: "聽起上嚟啱，但係錯調" },
        { time: "16:04", text: "And so at a certain point, as I got better at doing this,", translation: "所以某個時候，當我做得好啲" },
        { time: "16:06", text: "that's basically what started happening in my head.", translation: "基本上就係我腦中開始發生嘅" },
        { time: "16:09", text: "Just as I walked around and move through the world and listened to music,", translation: "就係我行嚟行去，聽音樂時" },
        { time: "16:13", text: "I was constantly automatically visualizing", translation: "我不斷自動可視化" },
        { time: "16:16", text: "these songs on a piano keyboard in my head.", translation: "呢啲歌喺我腦中鋼琴鍵盤上" },
        { time: "16:19", text: "But, you know, it was kind of a roll of the dice,", translation: "但，係有啲靠運" },
        { time: "16:22", text: "whether it was the correct key.", translation: "係咪正確調" },
        { time: "16:24", text: "And then if I found myself near a piano, I could figure out the key of the song", translation: "然後如果我近鋼琴，我可以搵到首歌調" },
        { time: "16:27", text: "and immediately transpose all those numbers into the correct key.", translation: "立即將所有數字轉換到正確調" },
        { time: "16:31", text: "So let's use one more example song and look at how that plays out.", translation: "所以我哋用多一個例子歌，睇下點樣進行" },
        { time: "16:33", text: "So here's the the introduction to from the start by levee.", translation: "所以呢個係Laufey嘅From the Start介紹" },
        { time: "16:42", text: "Now, when I hear that chord progression, I know what it is.", translation: "而家，當我聽到和弦進行，我知道係咩" },
        { time: "16:44", text: "It's a251.", translation: "係2-5-1" },
        { time: "16:46", text: "I don't know what key it's in, but I know that one is here, Bam!", translation: "我唔知係咩調，但我知道一喺度，Bam！" },
        { time: "16:51", text: "And I recognize the chord progression", translation: "我識別和弦進行" },
        { time: "16:53", text: "because I've learned so many songs in this style", translation: "因為我學咗好多呢個風格嘅歌" },
        { time: "16:56", text: "that often use this kind of 251 with these kind of chord extensions.", translation: "通常用呢種2-5-1同呢種和弦延伸" },
        { time: "17:01", text: "It's a minor nine chord dominant 13 chord and major seven chord.", translation: "係小九和弦、屬十三和弦同大七和弦" },
        { time: "17:06", text: "And you will definitely find this that the more songs", translation: "你肯定會發現越多歌" },
        { time: "17:08", text: "you learn in a certain style, the easier it is to recognize", translation: "你學某個風格，越容易識別" },
        { time: "17:11", text: "chord progressions that belong in that style.", translation: "屬於呢個風格嘅和弦進行" },
        { time: "17:13", text: "So if I hear a song like this, leave a song, I know what the numbers are,", translation: "所以如果我聽到首歌係咁，Laufey歌，我知道數字係咩" },
        { time: "17:18", text: "and I might even be imagining the song in my head in some key.", translation: "我甚至可能想像首歌喺某個調" },
        { time: "17:23", text: "Maybe I'd be imagining that in the key of F major.", translation: "可能我會想像F大調" },
        { time: "17:31", text: "It's not until I", translation: "直到我" },
        { time: "17:31", text: "get to a piano keyboard that I can play a reference pitch", translation: "去到鋼琴鍵盤先可以彈參考音" },
        { time: "17:34", text: "and then I know exactly what notes are being played", translation: "然後我知道確切彈緊咩音" },
        { time: "17:37", text: "and the way that that reference pitch thing works.", translation: "同參考音點樣運作" },
        { time: "17:39", text: "Once you're really comfortable with this,", translation: "一旦你對呢個好熟" },
        { time: "17:41", text: "is that you can just discretely play a single note.", translation: "係你可以偷偷彈單音" },
        { time: "17:45", text: "And if you've just been listening to the recording or the recordings playing,", translation: "如果你一直聽緊錄音或錄音播放緊" },
        { time: "17:48", text: "you can hear where that note lives within the key of the song.", translation: "你可以聽到個音喺首歌調中嘅位置" },
        { time: "17:52", text: "In this case, if I played a C and the song goes like that,", translation: "呢個情況，如果我彈C，首歌係咁" },
        { time: "17:56", text: "C is the seventh scale degree in the key of D flat major.", translation: "C係D♭大調第七個音階度數" },
        { time: "18:00", text: "And so I play this.", translation: "所以我彈呢個" },
        { time: "18:01", text: "I go, That's seven.", translation: "我話，係七" },
        { time: "18:02", text: "That means we must be in D flat.", translation: "即係一定係D♭" },
        { time: "18:05", text: "So you can get really good at this.", translation: "所以你可以做得好好" },
        { time: "18:06", text: "And this is where relative pitch starts to be almost indistinguishable", translation: "呢度相對音感開始幾乎分唔出" },
        { time: "18:10", text: "from perfect pitch because you can be really sneaky about your reference pitch.", translation: "同絕對音感，因為你可以好偷偷用參考音" },
        { time: "18:14", text: "And I got a lot of practice", translation: "我得到好多練習" },
        { time: "18:15", text: "with this when I used to accompany a church congregation in South L.A.", translation: "呢個，當我喺南L.A.伴奏教會會眾時" },
        { time: "18:19", text: "Sometimes they would just start singing things a cappella and I", translation: "有時佢哋會無伴奏開始唱，我" },
        { time: "18:23", text: "would have no idea what key they were in, but I need to figure it out really quick.", translation: "完全唔知係咩調，但我需要好快搵到" },
        { time: "18:26", text: "So I play a reference pitch here where it fit in the key", translation: "所以我彈參考音，佢適合調" },
        { time: "18:30", text: "that they were singing in, and then I'd launch in and", translation: "佢哋唱緊嘅，然後我會開始" },
        { time: "18:35", text: "whatever they were singing, I would find a way to accompany them.", translation: "無論佢哋唱咩，我會搵方法伴奏" },
        { time: "18:38", text: "So this is the most advanced level of the sort of step one", translation: "所以係第一步最高級水平" },
        { time: "18:41", text: "part of this three step process, finding the key of the song.", translation: "三步過程部分，搵首歌調" },
        { time: "18:44", text: "You know, you're going to get really comfortable", translation: "你會變得好好熟" },
        { time: "18:45", text: "with latching on to the sound of one for whatever song you're listening to.", translation: "抓住「一」嘅聲音，對任何你聽緊嘅歌" },
        { time: "18:50", text: "And then all you need in terms of a reference is one note.", translation: "然後你只需要一個音作為參考" },
        { time: "18:53", text: "Compare it to the sound of one in the key of the song,", translation: "比較佢同首歌調中「一」嘅聲音" },
        { time: "18:56", text: "and you'll be able to find what key you need to be in.", translation: "你就可以搵到需要係咩調" },
        { time: "18:58", text: "And then the rest of the process steps one through three, kind of get folded into", translation: "然後過程其餘步驟一到三，摺合成" },
        { time: "19:03", text: "one really fast thing that all happens in your ear once you get good at this.", translation: "一個好快嘅嘢，全部喺你隻耳發生，一旦你做得好" },
        { time: "19:09", text: "So when I'm just like listening", translation: "所以當我只係聽緊" },
        { time: "19:10", text: "to the radio, when it's music with relatively simple harmony,", translation: "收音機，當係相對簡單和聲音樂時" },
        { time: "19:14", text: "this kind of happens automatically in my head.", translation: "呢種自動喺我腦中發生" },
        { time: "19:16", text: "I'm hearing where the bases and I'm assigning numbers to things.", translation: "我聽到低音位置，分配數字" },
        { time: "19:19", text: "I've had students who have started getting good at doing this and told me", translation: "我有學生開始做得好，話我知" },
        { time: "19:23", text: "that they're getting annoyed by the fact that they can't turn it off.", translation: "佢哋好煩惱關唔到" },
        { time: "19:26", text: "And actually remember, there was there was a phase I went through where", translation: "其實記得，有個階段我經過" },
        { time: "19:29", text: "I was starting to get really good at doing this in college.", translation: "我開始做得好好，喺大學時" },
        { time: "19:32", text: "And I did find it almost interfered with my enjoyment of listening to music", translation: "我確實發現幾乎干擾我享受聽音樂" },
        { time: "19:36", text: "that I was just constantly like, What are the numbers?", translation: "我不斷問，數字係咩？" },
        { time: "19:39", text: "I was listening to everything to find the numbers.", translation: "我聽所有嘢搵數字" },
        { time: "19:41", text: "But the good news is that you'll move through that phase", translation: "但好消息係你會經過呢個階段" },
        { time: "19:44", text: "if you get to where every time you listen to music,", translation: "如果你去到每次聽音樂" },
        { time: "19:46", text: "you're trying to ID numbers and hear the chord progression,", translation: "你試緊識別數字同聽和弦進行" },
        { time: "19:49", text: "it will start to become so automatic that even if you can't stop yourself", translation: "會開始變得自動，就算你停唔到自己" },
        { time: "19:53", text: "from doing that,", translation: "做呢個" },
        { time: "19:54", text: "it will just be happening in the background and you can still go", translation: "只會背景發生，你仍然可以" },
        { time: "19:58", text: "back to listening to music very passively and just enjoying", translation: "返去被動聽音樂，只係享受" },
        { time: "20:01", text: "what you're hearing and not treating everything as an ear training exercise.", translation: "你聽到嘅，唔將所有嘢當聽力練習" },
        { time: "20:05", text: "So I hope this helps. You know, none of this is easy.", translation: "所以我希望幫到。你知道，呢啲都唔易" },
        { time: "20:08", text: "It all takes a lot of patience, but if you have the patience", translation: "全部需要好多耐心，但如果你有耐心" },
        { time: "20:12", text: "and you put in the effort, learning to play by ear", translation: "同你付出努力，學靠聽力彈" },
        { time: "20:14", text: "is something that is available to every musician.", translation: "係每個音樂人都可以做到" },
        { time: "20:17", text: "And it's such an amazing skill to have.", translation: "係好神奇嘅技能" },
        { time: "20:18", text: "It's really freeing to know that regardless of the piece of music,", translation: "好解放知道無論咩音樂" },
        { time: "20:22", text: "if you hear something, you're like,", translation: "如果你聽到嘢，你" },
        { time: "20:23", text: "you're going to be able to figure it out on your instrument.", translation: "會能夠喺你樂器上搵到" },
        { time: "20:25", text: "There's a lot I didn't cover in this video.", translation: "有好多我冇喺呢條片講" },
        { time: "20:27", text: "You know, there are other areas of your training,", translation: "你知道，有其他訓練範疇" },
        { time: "20:30", text: "like learning to separate out the timbres of different instruments or the sort of,", translation: "例如學分離唔同樂器音色或" },
        { time: "20:35", text: "you know, fine pitch hearing that we often don't even really develop as a pianist.", translation: "你知道，精細音高聽力，我哋作為鋼琴手通常唔會發展" },
        { time: "20:40", text: "But I've really had to work on", translation: "但我真係要努力" },
        { time: "20:41", text: "in the past couple of years since I've started learning violin.", translation: "過去幾年，自從我開始學小提琴" },
        { time: "20:44", text: "We also didn't touch on minor scales or other modes or scales at all,", translation: "我哋都冇講小調音階或其他調式或音階" },
        { time: "20:49", text: "and you will come across those even in popular music.", translation: "你會遇到，甚至流行音樂" },
        { time: "20:51", text: "But it's a great place to start just focusing on the major scale,", translation: "但係好起點只係專注大調音階" },
        { time: "20:54", text: "because I'd say 80 to 90% of pop songs are built around the major scale", translation: "因為我會話80到90%流行歌圍繞大調音階" },
        { time: "20:58", text: "or some sort of major tonality, and that's it.", translation: "或某種大調調性，就係咁" },
        { time: "21:00", text: "My name is Ted.", translation: "我係Ted" },
        { time: "21:02", text: "Remember to subscribe.", translation: "記得訂閱" },
        { time: "21:03", text: "If you want to see more tutorials like this,", translation: "如果你想睇更多呢類教程" },
        { time: "21:04", text: "if you have any questions on today's lesson, let me know in the comments.", translation: "如果你對今日課有問題，留言話我知" },
        { time: "21:08", text: "And in the meantime, happy practicing.", translation: "同時，練習愉快" }
    ],
    summary: {
        corePhilosophy: {
            title: "核心理念",
            text: "學習靠聽力彈琴並不需要絕對音感，事實上作者本人也沒有絕對音感，甚至無法在沒有參考音的情況下準確唱出 Middle C。℗然而，這項技能確實是可以培養的，熟練的音樂家可以在三十秒到一兩堂課的時間內就學會一首新歌。℗作者使用同一個三步過程已經許多年了，雖然過程本身保持不變，但執行能力會隨著練習逐漸提升。對於專業音樂人來說，這項技能幾乎是理所當然的基本能力。"
        },
        threeSteps: {
            title: "三步過程（通用）",
            text: "無論在哪個水平階段，靠聽力學習歌曲的核心過程都包含三個基本步驟：首先找出歌曲的調性，接著找出低音線，最後找出和弦。這三個步驟看似簡單，但隨著耳朵訓練程度的提升，每個步驟的執行方式會發生顯著的變化。"
        },
        beginnerLevel: {
            title: "初級水平",
            step1: {
                title: "第一步：找調（試錯法）",
                text: "在初級階段，找調的過程需要大量依賴試錯法，這是完全正常且可以接受的。首先，你需要認識大調音階，這是先決知識。不要害怕犯錯，因為彈錯音並不會弄壞樂器。℗最好的方法是與錄音一起彈奏，仔細聆聽哪些音聽起來是對的。即使未經訓練的耳朵也能做到這一點，你會逐漸收集到一系列屬於這首歌的音。℗例如，如果你發現 A、B、C# 和 E 這四個音都聽起來正確，那麼你就已經將可能的調性從十二個收窄到只有三個：A 大調、D 大調或 E 大調。℗接下來，你可以測試這些音階對錄音，聆聽解決感。當你彈奏音階到達頂音時，問問自己：這個音是否聽起來可以是歌曲的結尾？樂句或歌曲的結尾通常是最好的提示，因為作曲家經常在 I 和弦上結束。最終，會有一個音階特別「突出」，感覺完全屬於這首歌。"
            },
            step2: {
                title: "第二步：找低音線（bassline）",
                text: "一旦確定了調性，找低音線的工作就會變得容易許多。你已經將猜測從十二個可能的音高收窄到只有七個屬於音階的音。℗現在，你需要仔細聆聽和弦變化的地方，特別是在新和弦變化開始的瞬間，捕捉最低可以聽到的音。有兩個關鍵提示可以幫助你：℗首先，使用最好的耳機或喇叭，因為電話喇叭會切掉大量低頻，即使你的耳朵再好，也可能聽不到錄音中的低音。℗其次，在測試低音時，務必在樂器的低音域彈奏。如果彈得太高，旋律音會與低音產生摩擦，即使你猜對了低音，聽起來也會是錯的。例如在 Taylor Swift 的 Cruel Summer 中，最後一個低音是 D，而旋律同時有 C#，如果你在較高音域測試，兩者會互相干擾。℗特別是在新手階段，建議將找到的低音寫下來，以 Cruel Summer 為例，低音線是 A、C#、F#、D。"
            },
            step3: {
                title: "第三步：找和弦（chords）",
                text: "當你已經寫下低音並知道歌曲的調性後，找和弦的工作就變得相當直接了。每個低音只有幾個可能的和弦，這大大收窄了你的選擇範圍。℗你應該從自然音階和弦開始，也就是只使用音階內音的和弦。根據理論基礎，你可以做出合理的猜測：如果低音是 1，可能是大和弦；如果低音是 3，可能是小和弦；如果低音是 4，可能是大和弦；如果低音是 6，可能是小和弦。℗然後你可以測試這些猜測，與歌曲一起彈奏，看看是否聽起來正確。這就是知道調性的力量所在：基於調性的第一個猜測通常是正確的。℗作為額外的獎勵，你可以使用同樣的過程來找旋律，只需將猜測限制在音階音內即可。"
            }
        },
        intermediateLevel: {
            title: "中級水平",
            step1: {
                title: "第一步：找調（唱根音 root）",
                text: "在中級水平，你開始在測試鋼琴之前先尋找「一」的聲音。嘗試唱出一個聽起來已經解決的音，一個好像可以是歌曲結尾的音。樂句或歌曲的結尾通常包含最解決的音，這是尋找根音的最佳線索。℗一個常見的錯誤是，人們通常會唱出 1 或 5，因為兩者都聽起來穩定。但實際上，你比你想像中要好得多：你已經能夠認出哪些音聽起來是錯的或奇怪的，也能認出哪些東西聽起來屬於這首歌或是自然的結尾。你一生都在聽「一」的聲音，現在只是要為它命名，並在聽完一段音樂後能夠唱出來。℗要測試你的猜測，先唱出你懷疑的根音，然後在鋼琴上找到那個音，接著彈奏那個大調音階，看看是否屬於這首歌。最常見的錯誤是將 5 誤認為 1，但如果你選錯了，音階中會有一個音明顯不對。℗一個有用的提示是：唱出根音，然後唱周圍的音階音（例如 3-2-1-7-6-7-1-5-1），看看這是否與歌曲的聲音有道理。"
            },
            step2: {
                title: "第二步：找低音線（功能聽力訓練 functional ear training）",
                text: "在中級水平，找低音線的過程開始更多地依賴耳朵，而不是在樂器上測試。這就是所謂的功能聽力訓練，你會在特定調性中定位，然後用數字來識別音。在測試樂器之前，你試圖先聽出低音作為音階度數，也就是數字。℗有幾種方法可以練習這個技能：免費的「Functional Ears Trainer」應用程式是一個極好的工具，你也可以通過練習不同調性的旋律來建立這個能力，視唱是另一個很好的練習方法。當然，使用耳機或好喇叭仍然很重要。℗例如，在 Olivia Rodrigo 的 Vampire 這首歌中，你可能會聽到「一、三、四、四」，然後將這些數字轉換成調內的實際音。在 F 大調中，這些數字對應於 F、A、B♭（兩次）。"
            },
            step3: {
                title: "第三步：找和弦（測試前識別性質）",
                text: "在中級水平，你開始挑戰自己在測試樂器之前識別和弦的性質（大或小）。你可以依靠理論知識來收窄猜測：1 和弦通常是大的，3 和弦通常是小的（但在流行音樂中，3 和弦作為大和弦使用也很常見），4 和弦通常是大的。℗重要的是要記住，非自然音階和弦確實存在，也就是調外和弦。例如，3 和弦可能是大的而不是小的。℗隨著時間的推移，你會開始識別這些差異：3 小和弦和 3 大和弦有不同的聲音，3 大和弦有一種「強烈向上拉」的感覺。℗在測試之前寫下你的猜測，然後通過在鋼琴上測試來獲得反饋。通常，你只需要考慮大或小這兩個選項（之後可以擴展到轉位、七和弦等）。"
            },
            relativePitchAspect: {
                title: "相對音感（relative pitch）有趣方面",
                text: "相對音感有一個有趣的方面：當你發展出這種能力時，你會聽到所有東西作為數字，而且這些數字通常是準確的。然而，調性可能是錯的，你可能會在腦中可視化錯誤的調性。℗例如，你可能聽到一首歌，以為它是 C 調，並正確地可視化所有數字，但實際上調性是錯的。解決方法是：當你接近鋼琴時，找出實際的調性，然後將所有數字轉換到正確的調性。℗隨著練習，你會發現自己不斷在腦中自動可視化鋼琴鍵盤上的歌曲，這是一個自然的發展過程。"
            }
        },
        advancedLevel: {
            title: "高級水平",
            steps1to3: {
                title: "步驟 1-3：全部摺合成一個快速過程",
                text: "在高級水平，所有三個步驟會摺合成一個非常快速的過程，幾乎同時發生在你的耳朵中。你開始能夠即時識別和弦進行，例如聽到「這是 2-5-1」。℗你不僅能識別基本的和弦，還能識別和弦延伸，如小九和弦、屬十三和弦和大七和弦。風格識別變得越來越容易：你在同一風格中學的歌曲越多，就越容易識別該風格中的和弦進行。℗你可能會立即聽到數字，甚至可能在腦中想像某個調性（例如 F 大調），儘管實際調性可能不同。"
            },
            referencePitchMethod: {
                title: "參考音方法（reference pitch，偷偷參考音）",
                text: "一旦你對這個過程非常熟悉，你可以使用一個非常巧妙的方法：在錄音播放時偷偷彈奏一個單音。然後聆聽那個音在這首歌調性中的位置。℗例如，如果你彈奏 C，並意識到「這是 7」，那麼這首歌一定是 D♭ 大調。這種方法幾乎像絕對音感一樣有效，而且非常隱蔽和快速。℗這在實際應用中非常有用，例如在教會伴奏時，會眾可能會無伴奏開始唱歌，你需要快速找出調性並加入伴奏。"
            },
            automaticProcess: {
                title: "過程變自動",
                text: "隨著時間的推移，這個過程會變得完全自動化。當你聽收音機時，它會在背景中發生，你會自動聽到低音並分配數字。這個過程幾乎關不掉，但它會變成一個背景過程。℗在發展過程中，會有一個干擾階段：最初，這可能會干擾你對音樂的享受，因為你會不斷問自己「數字是什麼？」你會發現自己在聽所有東西時都在尋找數字。℗但好消息是，你會經過這個階段。最終，它會變成一個自動的背景過程，你可以回到被動聆聽和享受音樂，而不需要將所有東西都當作聽力訓練練習。"
            }
        },
        keyInsights: {
            title: "核心洞察",
            progressionPath: {
                title: "進步路徑",
                text: "進步的路徑是清晰的：在初級階段，你需要大量依賴試錯法，在樂器上測試所有東西。進入中級水平後，你會開始更多地基於耳朵工作，在測試之前先聆聽，並進行功能聽力訓練。最終達到高級水平時，識別會變得自動化，你可以使用參考音方法，所有步驟會快速同時發生。"
            },
            practiceRecommendations: {
                title: "練習建議",
                text: "有幾個特別有效的練習方法可以幫助你發展這些技能。免費的「Functional Ears Trainer」應用程式是功能聽力訓練的絕佳工具。℗練習不同調性的旋律可以幫助你建立音階度數識別能力。視唱是另一個發展功能聽力訓練的好方法。℗此外，學習同一風格的多首歌曲會讓識別該風格中的和弦進行變得更容易。"
            },
            importantNotes: {
                title: "重要注意事項",
                text: "值得注意的是，百分之八十到九十的流行歌曲使用大調音階或大調調性。因此，從大調音階開始是一個很好的起點，因為這已經涵蓋了絕大部分音樂。℗雖然小調音階和調式確實存在，但在流行音樂中相對少見。℗還有其他技能，如樂器音色分離和精細音高聽力，這些更多是小提琴手需要的技能，但對於鋼琴手來說通常不是必需的。"
            },
            finalThoughts: {
                title: "最後想法",
                text: "學習靠聽力彈琴需要耐心，因為這些技能都不容易掌握。但重要的是要記住，每個音樂人都可以做到這一點，這不只是有才華的人的專利。℗這是一項真正解放的技能，一旦掌握，無論你聽到什麼，都能在樂器上找到它。℗雖然這需要多年的練習，但過程本身保持不變，只是執行能力會隨著時間逐漸提升。"
            }
        },
        exampleSongs: {
            title: "使用的範例歌曲",
            text: "本教程使用了三個範例歌曲來示範不同水平的方法：Taylor Swift 的 Cruel Summer 作為初級範例，展示了基本的試錯法；Olivia Rodrigo 的 Vampire 作為中級範例，展示了功能聽力訓練的應用；Laufey 的 From the Start 作為高級範例，展示了對 2-5-1 進行等複雜和弦模式的即時識別。"
        }
    }
};
